/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import bank from './dbank.glb'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(bank)

  materials._glass.visible=false;
  return (
    <group {...props} ref={group} {...props} dispose={null}>
      <group position={[-4.94, 2.5, -5.04]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object.geometry} position={[236.78, 2.06, 74.85]} />
      </group>
      <group position={[-2.8, 2.5, 5.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object001.geometry} position={[278.08, -0.5, 74.85]} />
      </group>
      <group position={[-1.79, 2.1, 6.35]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object002.geometry} position={[257.76, 0.98, 34.85]} />
      </group>
      <group position={[10.98, 2.5, 2.19]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object003.geometry} position={[236.84, -0.5, 74.85]} />
      </group>
      <group position={[9.51, 2.5, 4.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object004.geometry} position={[278.08, -0.5, 74.85]} />
      </group>
      <group position={[8.18, 2.1, 6.35]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object005.geometry} position={[258.12, -0.5, 34.85]} />
      </group>
      <group position={[4.52, 4.48, 8.13]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object006.geometry} position={[0, -0.5, 0]} />
      </group>
      <group position={[4.54, 1.25, 8.15]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object007.geometry} position={[-52.36, -3.82, 0]} />
      </group>
      <group position={[4.52, 1.85, 8.13]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._glass} geometry={nodes.Object008.geometry} position={[65.52, -0.5, 9.85]} />
      </group>
      <group position={[4.54, 1.25, 8.1]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object009.geometry} position={[-91.44, -95.51, 1.91]} />
      </group>
      <group position={[8.08, 0.25, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object010.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[8.08, 2.75, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object011.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[9.29, 0.5, 3.15]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object012.geometry} position={[-90.42, -50, 36.57]} />
      </group>
      <group position={[0.96, 2.75, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object013.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[0.96, 0.25, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object014.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[8.23, 2, 6.3]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object015.geometry} position={[253.47, -5, 24.85]} />
      </group>
      <group position={[4.52, 3.58, 8.58]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Blue_Color} geometry={nodes.Object016.geometry} position={[50, -7.5, 0]} />
      </group>
      <group position={[4.52, 3.8, 8.58]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object017.geometry} position={[50, -15, 0]} />
      </group>
      <group position={[8.08, 0.45, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object018.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[0.96, 0.45, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object019.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[4.52, 4.48, 8.13]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object020.geometry} position={[0, -5, 0]} />
      </group>
      <group position={[4.52, 1.75, 8.13]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object021.geometry} position={[0.88, -5, 25]} />
      </group>
      <group position={[0.96, 5, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object022.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[0.96, 5.15, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object023.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[8.08, 5.15, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object024.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[8.08, 5, 7.98]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object025.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[8.18, 5.75, 8.08]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object026.geometry} position={[0, -75, 0]} />
      </group>
      <group position={[1.07, 6, 8.08]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object027.geometry} position={[0, -100, 0]} />
      </group>
      <group position={[4.52, 5.75, 8.23]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object028.geometry} position={[0, -15, 0]} />
      </group>
      <group position={[8.68, 4.07, 6.3]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Blue_Color} geometry={nodes.Object029.geometry} position={[50, -7.5, 199.08]} />
      </group>
      <group position={[8.68, 4.3, 6.3]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object030.geometry} position={[50, -15, 199.08]} />
      </group>
      <group position={[8.08, 2.5, 4.33]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh
          material={materials._Brick_Antique}
          geometry={nodes.Object031.geometry}
          position={[27.22, -150, 158.49]}
        />
      </group>
      <group position={[9.51, 2.5, 4.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object032.geometry} position={[278.08, -5, 74.85]} />
      </group>
      <group position={[10.67, 2.5, 3.77]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object033.geometry} position={[-5, -150, 5]} />
      </group>
      <group position={[11.02, 2.5, 2.14]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object034.geometry} position={[232.35, -5, 74.85]} />
      </group>
      <group position={[10.92, 0.25, 0.26]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object035.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[10.92, 0.45, 0.26]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object036.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[10.92, 2.75, 0.26]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object037.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[10.92, 0.25, -7.67]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object038.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[10.92, 0.45, -7.67]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object039.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[10.92, 2.75, -7.67]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object040.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[11.58, 1.75, -3.3]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object041.geometry} position={[0.88, -5, 25]} />
      </group>
      <group position={[7.57, 0.25, -12.44]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object042.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[7.57, 0.45, -12.44]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object043.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[7.57, 2.75, -12.44]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object044.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[-4.42, 0.25, -12.44]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object045.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[-4.42, 0.45, -12.44]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object046.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[-4.42, 2.75, -12.44]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object047.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[-2.28, 4.35, 6.3]} rotation={[0, 0, -Math.PI]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object048.geometry} position={[50, -15, 199.08]} />
      </group>
      <group position={[-4.42, 0.45, 2.28]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object049.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[-2.39, 0.5, 4.17]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object050.geometry} position={[-90.42, -50, 36.57]} />
      </group>
      <group position={[-1.83, 2, 6.3]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object051.geometry} position={[253.47, -5, 24.85]} />
      </group>
      <group position={[-4.42, 0.25, 2.28]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object052.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[-2.28, 4.13, 6.3]} rotation={[0, 0, -Math.PI]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Blue_Color} geometry={nodes.Object053.geometry} position={[50, -7.5, 199.08]} />
      </group>
      <group position={[-4.42, 2.75, 2.28]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object054.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[-2.8, 2.5, 5.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object055.geometry} position={[278.08, -5, 74.85]} />
      </group>
      <group position={[-3.97, 2.5, 4.79]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object056.geometry} position={[-5, -150, 5]} />
      </group>
      <group position={[-2.33, 2.5, 4.79]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object057.geometry} position={[-5, -150, 5]} />
      </group>
      <group position={[-0.81, 0.5, 7.72]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object058.geometry} position={[-19.3, -50, -70.11]} />
      </group>
      <group position={[-0.81, 1.5, 7.72]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object059.geometry} position={[-19.3, -50, -70.11]} />
      </group>
      <group position={[8.33, 5.47, 6.35]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object060.geometry} position={[-182.76, -15, -27.5]} />
      </group>
      <group position={[8.08, 5.75, 4.62]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object061.geometry} position={[0, -75, 0]} />
      </group>
      <group position={[-0.81, 5.75, 8.03]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object062.geometry} position={[-177.79, -15, 0]} />
      </group>
      <group position={[-1.73, 5.75, 8.8]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object063.geometry} position={[0, -15, 0]} />
      </group>
      <group position={[-1.73, 5.75, 8.33]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object064.geometry} position={[-177.79, -15, 0]} />
      </group>
      <group position={[8.08, 5, 4.62]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object065.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[8.08, 5.15, 4.62]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object066.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[4.01, 1.75, -13.11]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object067.geometry} position={[0.88, -5, 25]} />
      </group>
      <group position={[-5.03, 2.5, -0.59]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object068.geometry} position={[448.74, -150, -10]} />
      </group>
      <group position={[-4.98, 2.5, -5.08]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials.Black_Metal} geometry={nodes.Object069.geometry} position={[232.35, -5, 74.85]} />
      </group>
      <group position={[-5.03, 2.5, -9.57]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object070.geometry} position={[448.74, -150, -10]} />
      </group>
      <group position={[4.52, 5.75, 4.27]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object071.geometry} position={[0, -15, 0]} />
      </group>
      <group position={[0.71, 5.47, 6.35]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object072.geometry} position={[-182.76, -15, -27.5]} />
      </group>
      <group position={[1.07, 5.75, 4.62]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object073.geometry} position={[0, -75, 0]} />
      </group>
      <group position={[-15.6, 0.25, 2.48]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object074.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[-15.6, 0.45, 2.48]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object075.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[-15.6, 2.75, 2.48]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object076.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[-15.6, 0.45, -2.22]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object077.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[-15.6, 2.75, -2.22]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object078.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[-15.6, 0.25, -2.22]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object079.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[-6.3, 4.75, 2.84]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object080.geometry} position={[-177.79, -15, 0]} />
      </group>
      <group position={[-6.3, 4.75, -2.58]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object081.geometry} position={[-177.79, -15, 0]} />
      </group>
      <group position={[-16.96, 4.5, 0.13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.Color_D25} geometry={nodes.Object082.geometry} position={[646.42, -15, -25]} />
      </group>
      <group position={[-10.03, 0.45, 2.48]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object083.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[-10.03, 0.25, -2.22]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object084.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[-10.03, 0.45, -2.22]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._fascia_01} geometry={nodes.Object085.geometry} position={[0, 0, 0]} />
      </group>
      <group position={[-10.03, 0.25, 2.48]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Block} geometry={nodes.Object086.geometry} position={[0, -25, 0]} />
      </group>
      <group position={[-10.03, 2.75, -2.22]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object087.geometry} position={[0, -225, 0]} />
      </group>
      <group position={[-10.03, 2.75, 2.48]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh material={materials._Brick_Antique} geometry={nodes.Object088.geometry} position={[0, -225, 0]} />
      </group>
      <mesh
        material={materials._glass}
        geometry={nodes['Glass_-_08'].geometry}
        position={[4, 1.5, -13.09]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._glass}
        geometry={nodes['Glass_-_05'].geometry}
        position={[11.53, 1.5, -3.31]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Line1863.geometry}
        position={[9.6, 0.95, 3.54]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._Brick_Block}
        geometry={nodes.Line1873.geometry}
        position={[10.31, 0, -10.89]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._Brick_Antique}
        geometry={nodes.Line1874.geometry}
        position={[10.31, 1, -10.89]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Line1886.geometry}
        position={[-2.9, 0.95, 4.56]}
        rotation={[Math.PI, 1.57, 0]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Line1895.geometry}
        position={[-0.26, 0.95, 7.4]}
        rotation={[Math.PI, 1.57, 0]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Line1898.geometry}
        position={[9.83, 4, -3.98]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Line1908.geometry}
        position={[4.52, 6.5, 6.14]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._Brick_Block}
        geometry={nodes.Line1912.geometry}
        position={[-5.13, 0, -5.08]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Line1913.geometry}
        position={[-5.13, 0.95, -5.08]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials.Color_D25}
        geometry={nodes.Line1917.geometry}
        position={[9.83, 4.5, -3.98]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Line1918.geometry}
        position={[9.83, 6, -3.98]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._roof_03}
        geometry={nodes.Line1919.geometry}
        position={[4.1, 6, 0.33]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._metal_black_roof}
        geometry={nodes.Line1923.geometry}
        position={[4.52, 7.1, 6.25]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._roof_03}
        geometry={nodes.Rectangle634.geometry}
        position={[-10.97, 4.5, 0.13]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._Blue_Color}
        geometry={nodes.Text013.geometry}
        position={[4.13, 5.43, 8.37]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Object351.geometry}
        position={[4.13, 5.43, 8.37]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Object352.geometry}
        position={[11.61, 4.93, -3.49]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._Blue_Color}
        geometry={nodes.Text014.geometry}
        position={[11.61, 4.93, -3.49]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._white_greyscale}
        geometry={nodes.Line1939.geometry}
        position={[4.46, 0, -0.18]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials._fascia_01}
        geometry={nodes.Text013001.geometry}
        position={[4.13, 5.43, 8.37]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['_fascia_01.001']}
        geometry={nodes.Text013002.geometry}
        position={[11.62, 4.93, -3.49]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload(bank)
