/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import kfc from './dkfc2.glb'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(kfc)
  return (
    <group {...props} ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.door_frame_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.door3_1_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.jalousie3_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.jalousie4_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.jalousie5_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.jalousie2_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.air_conditioning2_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.jalousie8_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.jalousie7_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.jalousie6_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.back_door_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.roof_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.exterior_walls2_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.jalousie1_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.lighting_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.air_conditioning1_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.roof_details_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.logo3_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.exterior_texts_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.overlap_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.overlap_fixing_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.Ceiling_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.flooring_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.glass_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.flooring2_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.inner_walls_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.windows_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.fencing_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.front_door2_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.front_door1_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.exterior_walls3_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
      <mesh
        material={materials['Fast_Food_Restaurant.001']}
        geometry={nodes.exterior_walls1_pivot001.geometry}
        rotation={[0, 1.57, 0]}
        scale={[0.08, 0.08, 0.08]}
      />
    </group>
  )
}

useGLTF.preload(kfc)
