/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import qsr from './dqsr.glb'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(qsr)
  return (
    <group {...props} ref={group} {...props} dispose={null}>
      <group position={[13.66, 1.47, -15.85]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <group position={[7.06, -29.28, 10.24]}>
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222162.geometry}
            position={[-0.96, 12.58, 0.02]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222163.geometry}
            position={[4.15, -8.85, 0]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222164.geometry}
            position={[-1.18, 12.58, 0.02]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222165.geometry}
            position={[4.15, -33.82, 0]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222166.geometry}
            position={[4.15, 6.83, 0]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222167.geometry}
            position={[-1.18, -12.32, 0.02]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222168.geometry}
            position={[-0.96, -12.32, 0.02]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
        </group>
        <group position={[7.06, -29.28, -9.49]}>
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222169.geometry}
            position={[-1.18, -12.32, 0.02]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222170.geometry}
            position={[-0.96, 12.58, 0.02]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222171.geometry}
            position={[4.15, -8.85, 0]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222172.geometry}
            position={[-1.18, 12.58, 0.02]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222173.geometry}
            position={[4.15, 6.83, 0]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222174.geometry}
            position={[4.15, -33.82, 0]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
          <mesh
            material={materials['KROM.002']}
            geometry={nodes.Line2029222175.geometry}
            position={[-0.96, -12.32, 0.02]}
            rotation={[-Math.PI / 2, 0, 3.14]}
            scale={[-1, -1, -1]}
          />
        </group>
        <mesh
          material={materials['wood_18UssaSDFDFFF.002']}
          geometry={nodes.Box2131682035.geometry}
          position={[1.52, -16.46, -37.5]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          material={materials['wood_18UssaSDFDFFF.002']}
          geometry={nodes.Box2131682036.geometry}
          position={[1.52, -16.46, 37.52]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          material={materials['wood_18UssaSDFDFFF.002']}
          geometry={nodes.Line2029222161.geometry}
          position={[0.46, -13.96, 0]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
      </group>
      <group position={[8.53, 1.4, 1.62]} scale={[0.01, 0.01, 0.01]}>
        <group position={[-804.45, 0, -284.01]} rotation={[0, -1.57, 0]}>
          <mesh
            material={materials['glass.002']}
            geometry={nodes.Box2131682290.geometry}
            position={[0.01, 0, -0.25]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['pen frame.002']}
            geometry={nodes.Plane11688.geometry}
            position={[0.01, 0, -4]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group position={[-474.45, 0, 530]}>
          <mesh
            material={materials['glass.002']}
            geometry={nodes.Box2131682297.geometry}
            position={[0.01, 0, -0.25]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['pen frame.002']}
            geometry={nodes.Plane11689.geometry}
            position={[0.01, 0, -4]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group position={[95.55, 0, 530]}>
          <mesh
            material={materials['glass.002']}
            geometry={nodes.Box2131682301.geometry}
            position={[0.01, 0, -0.25]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['pen frame.002']}
            geometry={nodes.Plane11690.geometry}
            position={[0.01, 0, -4]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group position={[615.55, 0, 530]}>
          <mesh
            material={materials['glass.002']}
            geometry={nodes.Box2131682304.geometry}
            position={[0.01, 0, -0.25]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['pen frame.002']}
            geometry={nodes.Plane11691.geometry}
            position={[0.01, 0, -4]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group position={[-810, 0, 231]}>
          <group position={[-1.26, -30, 40]} rotation={[0, 0, -Math.PI]} scale={[-1, -1, -1]}>
            <mesh
              material={materials['pen frame.002']}
              geometry={nodes.Plane11686.geometry}
              position={[4.3, 0, 0]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Rectangle1410076891.geometry}
              position={[-3.62, -8.86, 36.33]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[0.62, 0.62, 0.62]}
            />
          </group>
          <group position={[-1.26, -30, -40]}>
            <mesh
              material={materials['pen frame.002']}
              geometry={nodes.Plane11685.geometry}
              position={[4.3, 0, 0]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Rectangle1410076890.geometry}
              position={[-3.62, -8.86, 36.33]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[0.62, 0.62, 0.62]}
            />
          </group>
          <group position={[1.55, 0, 0]}>
            <mesh
              material={materials['glass.002']}
              geometry={nodes.Box2131682289.geometry}
              position={[0.26, 0, 0]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
              material={materials['pen frame.002']}
              geometry={nodes.Plane11687.geometry}
              position={[4.01, 0, 0]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
            />
          </group>
        </group>
      </group>
      <group position={[14.42, 2.88, -16.46]} rotation={[Math.PI, 0, Math.PI]} scale={[0.01, 0.01, 0.01]}>
        <mesh
          material={materials['blue.002']}
          geometry={nodes.Box2131682348.geometry}
          position={[-400.81, -31.59, 2.17]}
          scale={[0.78, 1.06, 1.06]}
        />
        <mesh
          material={materials['vrayws.002']}
          geometry={nodes.Line2029222418.geometry}
          position={[643.02, 0.54, -1056.03]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.78, 1.09, 1.06]}
        />
      </group>
      <group position={[8.47, 2.91, 1.78]} scale={[0.01, 0.01, 0.01]}>
        <group position={[-768.33, 0, 566.81]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.flanez269.geometry}
            position={[0, -42.66, -17.56]}
            rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
            scale={[-31.27, -31.27, -31.27]}
          />
          <mesh
            material={materials['light2.002']}
            geometry={nodes.Rectangle1410076893.geometry}
            position={[-1.86, -13.17, 19.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.84, 0.84, 0.84]}
          />
        </group>
        <group position={[-183.09, 0, 566.81]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.flanez270.geometry}
            position={[0, -42.66, -17.56]}
            rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
            scale={[-31.27, -31.27, -31.27]}
          />
          <mesh
            material={materials['light2.002']}
            geometry={nodes.Rectangle1410076894.geometry}
            position={[-1.86, -13.17, 19.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.84, 0.84, 0.84]}
          />
        </group>
        <group position={[335.38, 0, 566.81]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.flanez271.geometry}
            position={[0, -42.66, -17.56]}
            rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
            scale={[-31.27, -31.27, -31.27]}
          />
          <mesh
            material={materials['light2.002']}
            geometry={nodes.Rectangle1410076895.geometry}
            position={[-1.86, -13.17, 19.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.84, 0.84, 0.84]}
          />
        </group>
        <group position={[873.41, 0, 566.81]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.flanez272.geometry}
            position={[0, -42.66, -17.56]}
            rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
            scale={[-31.27, -31.27, -31.27]}
          />
          <mesh
            material={materials['light2.002']}
            geometry={nodes.Rectangle1410076896.geometry}
            position={[-1.86, -13.17, 19.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.84, 0.84, 0.84]}
          />
        </group>
        <group position={[-853.78, 0, 493.28]} rotation={[0, -1.57, 0]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.flanez273.geometry}
            position={[0, -42.66, -17.56]}
            rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
            scale={[-31.27, -31.27, -31.27]}
          />
          <mesh
            material={materials['light2.002']}
            geometry={nodes.Rectangle1410076897.geometry}
            position={[-1.86, -13.17, 19.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.84, 0.84, 0.84]}
          />
        </group>
        <group position={[-853.78, 0, -64.31]} rotation={[0, -1.57, 0]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.flanez274.geometry}
            position={[0, -42.66, -17.56]}
            rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
            scale={[-31.27, -31.27, -31.27]}
          />
          <mesh
            material={materials['light2.002']}
            geometry={nodes.Rectangle1410076898.geometry}
            position={[-1.86, -13.17, 19.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.84, 0.84, 0.84]}
          />
        </group>
        <group position={[-853.78, 0, -586.45]} rotation={[0, -1.57, 0]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.flanez275.geometry}
            position={[0, -42.66, -17.56]}
            rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
            scale={[-31.27, -31.27, -31.27]}
          />
          <mesh
            material={materials['light2.002']}
            geometry={nodes.Rectangle1410076899.geometry}
            position={[-1.86, -13.17, 19.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.84, 0.84, 0.84]}
          />
        </group>
      </group>
      <group position={[8.99, 3.8, -4.37]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials['r34.002']} geometry={nodes.kesıt.geometry} position={[0, 175.53, 377.12]} />
        <mesh
          material={materials['r34.002']}
          geometry={nodes.Line2029222407.geometry}
          position={[0.01, 135, -951.21]}
        />
        <mesh material={materials['tac.002']} geometry={nodes.Line2029222409.geometry} position={[0, -10, 378.79]} />
        <mesh material={materials['tac.002']} geometry={nodes.Line2029222410.geometry} position={[0, 152.62, 378.79]} />
        <mesh material={materials['tac.002']} geometry={nodes.Line2029222411.geometry} position={[0, 133.52, 378.79]} />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222413.geometry}
          position={[1700, -235, -771.21]}
        />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222414.geometry}
          position={[1735.32, -254.67, 399.11]}
        />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222415.geometry}
          position={[1735.01, -255, 918.79]}
        />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222416.geometry}
          position={[-1699.99, -235, -771.21]}
          rotation={[Math.PI, 0, 0]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222417.geometry}
          position={[-11.66, -235, -2024.54]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222420.geometry}
          position={[-15.36, -10, -1488.07]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222421.geometry}
          position={[-0.25, -10, -318.03]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222422.geometry}
          position={[-0.25, -10, 201.77]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['tac.002']}
          geometry={nodes.Line2029222423.geometry}
          position={[-1625.16, -10, -1488.07]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </group>
      <group position={[9.16, 2.96, -5.08]} scale={[0.01, 0.01, 0.01]}>
        <group position={[836.7, 0, 1104.13]}>
          <group position={[28.06, -29.15, 0]} rotation={[Math.PI, 1.57, 0]} scale={[-1, -1, -1]}>
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Box2131682352.geometry}
              position={[0.23, 227.82, 15.85]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              material={materials['wr1f34.002']}
              geometry={nodes.Plane11697.geometry}
              position={[0.2, 32.73, 9.82]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1, -1, -1]}
            />
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Plane11698.geometry}
              position={[0.27, 72.33, 10]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1.03, -1.03, -0.68]}
            />
          </group>
          <mesh
            material={materials['aluminium_02s.004']}
            geometry={nodes.Box2131682363.geometry}
            position={[-30.66, 272.82, -3.95]}
            rotation={[-Math.PI, 0, 0]}
          />
        </group>
        <group position={[809.24, -20.77, 4.72]}>
          <group position={[20.6, -8.38, 0]} rotation={[Math.PI, 1.57, 0]} scale={[-1, -1, -1]}>
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Box2131682351.geometry}
              position={[0.23, 227.82, 15.85]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              material={materials['wr1f34.002']}
              geometry={nodes.Plane11695.geometry}
              position={[0.2, 32.73, 9.82]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1, -1, -1]}
            />
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Plane11696.geometry}
              position={[0.27, 72.33, 10]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1.03, -1.03, -0.68]}
            />
          </group>
          <mesh
            material={materials['aluminium_02s.004']}
            geometry={nodes.Box2131682361.geometry}
            position={[-23.21, 245.79, -3.65]}
            rotation={[-Math.PI, 0, 0]}
          />
        </group>
        <group position={[708.15, -20.77, -1078.84]}>
          <group position={[0.05, -8.38, -22.45]}>
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Box2131682353.geometry}
              position={[0.23, 227.82, 15.85]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              material={materials['wr1f34.002']}
              geometry={nodes.Plane11699.geometry}
              position={[0.2, 32.73, 9.82]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1, -1, -1]}
            />
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Plane11700.geometry}
              position={[0.27, 72.33, 10]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1.03, -1.03, -0.68]}
            />
          </group>
          <mesh
            material={materials['aluminium_02s.004']}
            geometry={nodes.Box2131682360.geometry}
            position={[0.18, 245.79, 22.53]}
            rotation={[-Math.PI, 0, 0]}
          />
        </group>
        <group position={[-844.54, -20.77, 4.72]}>
          <group position={[-20.22, -8.38, 0]} rotation={[0, 1.57, 0]}>
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Box2131682350.geometry}
              position={[0.23, 227.82, 15.85]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              material={materials['wr1f34.002']}
              geometry={nodes.Plane11693.geometry}
              position={[0.2, 32.73, 9.82]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1, -1, -1]}
            />
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Plane11694.geometry}
              position={[0.27, 72.33, 10]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1.03, -1.03, -0.68]}
            />
          </group>
          <mesh
            material={materials['aluminium_02s.004']}
            geometry={nodes.Box2131682362.geometry}
            position={[23.3, 245.79, -3.65]}
            rotation={[-Math.PI, 0, 0]}
          />
        </group>
        <group position={[-717.59, -20.77, -1078.84]}>
          <group position={[0, -8.38, -22.45]}>
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Box2131682349.geometry}
              position={[0.23, 227.82, 15.85]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              material={materials['wr1f34.002']}
              geometry={nodes.Plane11655.geometry}
              position={[0.2, 32.73, 9.82]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1, -1, -1]}
            />
            <mesh
              material={materials['aluminium_02s.004']}
              geometry={nodes.Plane11656.geometry}
              position={[0.27, 72.33, 10]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-1.03, -1.03, -0.68]}
            />
          </group>
          <mesh
            material={materials['aluminium_02s.004']}
            geometry={nodes.Box2131682359.geometry}
            position={[0.23, 245.79, 22.53]}
            rotation={[-Math.PI, 0, 0]}
          />
        </group>
      </group>
      <group position={[6.49, 0.08, -3.02]} scale={[0.01, 0.01, 0.01]}>
        <mesh
          material={materials['Material #1sEFsc.016']}
          geometry={nodes.Box2131682356.geometry}
          position={[250, -7.5, -150]}
        />
      </group>
      <group position={[0.46, 0.67, 4.2]} scale={[0.01, 0.01, 0.01]}>
        <group position={[-34.3, 0, -218.69]} rotation={[0, Math.PI / 2, 0]} scale={[0.99, 0.83, 0.99]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes['garbage-009'].geometry}
            position={[0, -44.56, 0]}
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.garbage006.geometry}
            position={[0, -4.7, 0]}
            rotation={[Math.PI / 2, 0, Math.PI]}
          />
        </group>
        <group position={[23.16, 0, 222.27]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.99, 0.83, 0.99]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes['garbage-010'].geometry}
            position={[0, -44.56, 0]}
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.garbage007.geometry}
            position={[0, -4.7, 0]}
            rotation={[Math.PI / 2, 0, Math.PI]}
          />
        </group>
      </group>
      <group position={[8.99, 5.35, 1.33]} scale={[0.01, 0.01, 0.01]}>
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Box2131682345.geometry}
          position={[545.01, -20, 554.99]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44959.geometry}
          position={[850.01, -20, 1427.86]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44960.geometry}
          position={[850.02, -20, 867.86]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44961.geometry}
          position={[-817.5, -20, -537.51]}
          rotation={[0, 0, Math.PI]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44962.geometry}
          position={[817.52, -20, -22.5]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44963.geometry}
          position={[-817.5, -20.01, -17.5]}
          rotation={[0, 0, Math.PI]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44964.geometry}
          position={[287.51, -20, 522.48]}
          rotation={[-Math.PI, 1.57, 0]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44965.geometry}
          position={[817.5, -20, 537.5]}
          rotation={[Math.PI, 0, 0]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44966.geometry}
          position={[-817.5, -20, 537.5]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44967.geometry}
          position={[817.5, -20, -537.5]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['sand_wall.002']}
          geometry={nodes.Object44968.geometry}
          position={[-232.5, -20, 522.49]}
          rotation={[-Math.PI, 1.57, 0]}
          scale={[-1, -1, -1]}
        />
      </group>
      <group position={[8.28, 4.47, 1.94]} scale={[0.01, 0.01, 0.01]}>
        <group position={[-841.49, -4.86, -596.94]} rotation={[0, -1.57, 0]} scale={[0.67, 0.67, 0.67]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder210815.geometry}
            position={[0, 1.75, -69.96]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder210816.geometry}
            position={[0, 1.75, -68.04]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder9142.geometry}
            position={[7.98, 0, 21.63]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.69, -1.06, -0.69]}
          />
          <mesh
            material={materials['burger.002']}
            geometry={nodes.Object43705.geometry}
            position={[7.98, 0, 21.63]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[0.69, 1.06, 0.69]}
          />
          <mesh
            material={materials['burger.002']}
            geometry={nodes.Object43706.geometry}
            position={[7.98, 0, 21.63]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.69, -1.06, -0.69]}
          />
        </group>
        <group position={[-746.11, -4.86, 556.53]} scale={[0.67, 0.67, 0.67]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder210826.geometry}
            position={[7.98, 0, 21.63]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.69, -1.06, -0.69]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder210827.geometry}
            position={[0, 1.75, -68.04]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder210828.geometry}
            position={[0, 1.75, -69.96]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['burger.002']}
            geometry={nodes.Object44972.geometry}
            position={[7.98, 0, 21.63]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[0.69, 1.06, 0.69]}
          />
          <mesh
            material={materials['burger.002']}
            geometry={nodes.Object44973.geometry}
            position={[7.98, 0, 21.63]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.69, -1.06, -0.69]}
          />
        </group>
        <group position={[881.9, -4.86, 556.53]} scale={[0.67, 0.67, 0.67]}>
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder210829.geometry}
            position={[7.97, 0, 21.63]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.69, -1.06, -0.69]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder210830.geometry}
            position={[0, 1.75, -68.04]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Cylinder210831.geometry}
            position={[0, 1.75, -69.96]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            material={materials['burger.002']}
            geometry={nodes.Object44974.geometry}
            position={[7.97, 0, 21.63]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[0.69, 1.06, 0.69]}
          />
          <mesh
            material={materials['burger.002']}
            geometry={nodes.Object44975.geometry}
            position={[7.97, 0, 21.63]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.69, -1.06, -0.69]}
          />
        </group>
        <group position={[-794.23, -34.09, -77.11]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
          <mesh material={materials['krem light.002']} geometry={nodes.Mesh488.geometry} />
          <mesh material={materials['Material #2146025624.002']} geometry={nodes.Mesh488_1.geometry} />
        </group>
        <group position={[101.18, -34.09, 509.45]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['krem light.002']} geometry={nodes.Mesh494.geometry} />
          <mesh material={materials['Material #2146025624.002']} geometry={nodes.Mesh494_1.geometry} />
        </group>
      </group>
      <group position={[7.94, 3.09, 2.24]} scale={[0.01, 0.01, 0.01]}>
        <group position={[155.53, 0, 535.96]}>
          <mesh
            material={materials['blue.002']}
            geometry={nodes.Box2131682299.geometry}
            position={[-400.81, -31.59, 2.17]}
            scale={[0.78, 1.06, 1.06]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Line2029222405.geometry}
            position={[643.02, 0.54, -1056.03]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[0.78, 1.09, 1.06]}
          />
        </group>
        <group position={[-816.3, 0, -394.76]} rotation={[0, -1.57, 0]}>
          <mesh
            material={materials['blue.002']}
            geometry={nodes.Box2131682285.geometry}
            position={[-400.81, -31.59, 2.17]}
            scale={[0.78, 1.06, 1.06]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Line2029222403.geometry}
            position={[643.02, 0.54, -1056.03]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[0.78, 1.09, 1.06]}
          />
        </group>
        <group position={[-816.3, 0, 166.42]} rotation={[0, -1.57, 0]}>
          <mesh
            material={materials['blue.002']}
            geometry={nodes.Box2131682286.geometry}
            position={[-400.81, -31.59, 2.17]}
            scale={[0.78, 1.06, 1.06]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Line2029222402.geometry}
            position={[643.02, 0.54, -1056.03]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[0.78, 1.09, 1.06]}
          />
        </group>
        <group position={[-414.17, 0, 535.96]}>
          <mesh
            material={materials['blue.002']}
            geometry={nodes.Box2131682295.geometry}
            position={[-400.81, -31.59, 2.17]}
            scale={[0.78, 1.06, 1.06]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Line2029222404.geometry}
            position={[643.02, 0.54, -1056.03]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[0.78, 1.09, 1.06]}
          />
        </group>
        <group position={[675.67, 0, 535.96]}>
          <mesh
            material={materials['blue.002']}
            geometry={nodes.Box2131682302.geometry}
            position={[-400.81, -31.59, 2.17]}
            scale={[0.78, 1.06, 1.06]}
          />
          <mesh
            material={materials['krem light.002']}
            geometry={nodes.Line2029222406.geometry}
            position={[643.02, 0.54, -1056.03]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[0.78, 1.09, 1.06]}
          />
        </group>
      </group>
      <group position={[8.51, 3.9, 1.66]} scale={[0.01, 0.01, 0.01]}>
        <mesh
          material={materials['Material.001']}
          geometry={nodes.Box2131682303.geometry}
          position={[592.7, -125, 522.3]}
        />
        <group position={[-769.8, -20.01, -50.2]} rotation={[0, 0, Math.PI]} scale={[-1, -1, -1]}>
          <mesh material={materials['sand_wall.002']} geometry={nodes.Mesh511.geometry} />
          <mesh material={materials['223323.002']} geometry={nodes.Mesh511_1.geometry} />
        </group>
        <group position={[-184.8, -20, 489.8]} rotation={[-Math.PI, 1.57, 0]} scale={[-1, -1, -1]}>
          <mesh material={materials['sand_wall.002']} geometry={nodes.Mesh513.geometry} />
          <mesh material={materials['223323.002']} geometry={nodes.Mesh513_1.geometry} />
        </group>
        <group position={[335.2, -20.01, 489.79]} rotation={[-Math.PI, 1.57, 0]} scale={[-1, -1, -1]}>
          <mesh material={materials['sand_wall.002']} geometry={nodes.Mesh512.geometry} />
          <mesh material={materials['223323.002']} geometry={nodes.Mesh512_1.geometry} />
        </group>
      </group>
      <group position={[8.99, 4.43, -4.52]} scale={[0.01, 0.01, 0.01]}>
        <mesh
          material={materials['tfr.002']}
          geometry={nodes.Box2131682337.geometry}
          position={[-802.51, -72.5, -1122.7]}
          rotation={[0, 0, Math.PI]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['tfr.002']}
          geometry={nodes.Box2131682339.geometry}
          position={[802.49, -72.5, -1122.7]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['tfr.002']}
          geometry={nodes.Object.geometry}
          position={[817.49, -72.5, 1122.3]}
          rotation={[Math.PI, 0, 0]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['tfr.002']}
          geometry={nodes.Object44952.geometry}
          position={[-817.51, -72.5, 1122.3]}
        />
        <mesh
          material={materials['tfr.002']}
          geometry={nodes.Object44953.geometry}
          position={[-817.51, -72.5, 47.3]}
          rotation={[0, 0, Math.PI]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['tfr.002']}
          geometry={nodes.Object44958.geometry}
          position={[817.49, -72.5, 47.3]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1, -1, -1]}
        />
        <mesh
          material={materials['tfr.002']}
          geometry={nodes.Object44978.geometry}
          position={[817.49, -72.5, 47.3]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-1, -1, -1]}
        />
      </group>
      <mesh
        material={materials['sand_wall.002']}
        geometry={nodes.Box2131682293.geometry}
        position={[17.49, 0.15, 3.93]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682322.geometry}
        position={[6.64, 0.15, 6.58]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682324.geometry}
        position={[11.84, 0.15, 6.58]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682325.geometry}
        position={[17.19, 3.74, 6.73]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682327.geometry}
        position={[0.79, 0.15, 1.13]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682329.geometry}
        position={[0.79, 0.15, -4.07]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682334.geometry}
        position={[17.19, 0.15, 1.13]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682336.geometry}
        position={[17.19, 0.15, -4.07]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682338.geometry}
        position={[0.94, 3.71, -15.77]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682340.geometry}
        position={[17.04, 0.15, -15.77]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group position={[8.99, 5.15, -10.09]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials['tavan.002']} geometry={nodes.Mesh391.geometry} />
        <mesh material={materials['017_WFloor_Stripe_Willow_2YS.004']} geometry={nodes.Mesh391_1.geometry} />
      </group>
      <mesh
        material={materials['sand_wall.002']}
        geometry={nodes.Box2131682343.geometry}
        position={[17.14, 0.15, -9.92]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['sand_wall.002']}
        geometry={nodes.Box2131682344.geometry}
        position={[17.49, 0.15, -1.47]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['sand_wall.002']}
        geometry={nodes.Box2131682346.geometry}
        position={[0.84, 5.16, -9.92]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <mesh
        material={materials['sand_wall.002']}
        geometry={nodes.Box2131682347.geometry}
        position={[11.04, 0.15, -15.77]}
        rotation={[0, 1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['aluminium_02s.004']}
        geometry={nodes.Plane11692.geometry}
        position={[15.08, 0.82, -16.32]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material #2143743221.005']}
        geometry={nodes.Box2131682366.geometry}
        position={[0.79, 0.15, 6.73]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['aluminium_02s.004']}
        geometry={nodes.Line2029222424.geometry}
        position={[9, 5.68, 1.28]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload(qsr)
