/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import dnsc from './dnsc.glb'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(dnsc)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['default']} geometry={nodes.Plane001.geometry} position={[4.0708, 0.1, 2.5311]}>
        <mesh
          material={materials['default']}
          geometry={nodes.BG10C1.geometry}
          position={[-0.9901, 0.5276, -1.557]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}>
          <mesh
            material={materials['default']}
            geometry={nodes.BG10C1Glass.geometry}
            position={[224.8511, 62.3783, 250.96]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
        </mesh>
        <mesh
          material={materials['default']}
          geometry={nodes.Block1_Trees.geometry}
          position={[-1.2658, 0.3195, -12.9022]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0536, 0.0666, 0.0536]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block1StreetDetails01.geometry}
          position={[0.6385, 0.3437, -2.6553]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block3.geometry}
          position={[-6.5474, 0.3437, -0.2367]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Glass2KC9BG19.geometry}
          position={[-1.2258, 0.4376, 1.1666]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC3BG13.geometry}
          position={[1.5239, 0.7964, 0.5079]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC4BG06.geometry}
          position={[1.1962, 1.0946, 1.8857]}
          rotation={[1.5708, 0, 0]}
          scale={[0.0012, 0.0013, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC4BG16.geometry}
          position={[1.2091, 0.4447, -2.3386]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0014, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC7BG10.geometry}
          position={[1.4273, 0.7056, -0.068]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0015, 0.0017, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC9BG19.geometry}
          position={[-0.7074, 3.9487, 1.0911]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.0013, -0.0015, -0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC3BG13.geometry}
          position={[0.6449, 0.8179, 1.2363]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC4BG06.geometry}
          position={[1.1923, 1.4819, 1.4708]}
          scale={[0.0012, 0.0014, 0.0013]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC4BG16.geometry}
          position={[1.025, 0.7741, -1.4953]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0015, 0.0015, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC7BG10.geometry}
          position={[0.7101, 0.35, 0.5259]}
          rotation={[0, 1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0017]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC9BG19.geometry}
          position={[-1.0338, 1.2742, 0.7945]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0013, 0.0014, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC9BG19Blinds.geometry}
          position={[-0.7115, 0.9238, 0.935]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-0.0013, -0.0015, -0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object01.geometry}
          position={[-1.0338, 1.2742, 0.7953]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
      </mesh>
      <mesh material={materials['default']} geometry={nodes.Plane002.geometry} position={[-1.7, 0.1, -3.24]}>
        <mesh
          material={materials['default']}
          geometry={nodes.BG10C1001.geometry}
          position={[-0.9901, 0.5276, -1.557]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}>
          <mesh
            material={materials['default']}
            geometry={nodes.BG10C1Glass001.geometry}
            position={[224.8507, 62.3783, 250.9597]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
        </mesh>
        <mesh
          material={materials['default']}
          geometry={nodes.Block1_Trees001.geometry}
          position={[-1.2658, 0.3195, -12.5622]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0536, 0.0666, 0.0536]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block1StreetDetails01001.geometry}
          position={[0.6385, 0.3437, -2.6553]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block3001.geometry}
          position={[-6.5474, 0.3437, -0.2367]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Glass2KC9BG19001.geometry}
          position={[-1.2258, 0.4376, 1.1666]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC3BG13001.geometry}
          position={[1.5239, 0.7964, 0.5079]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC4BG06001.geometry}
          position={[1.1963, 1.0946, 1.8857]}
          rotation={[1.5708, 0, 0]}
          scale={[0.0012, 0.0013, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC7BG10001.geometry}
          position={[1.4273, 0.7056, -0.068]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0015, 0.0017, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC9BG19001.geometry}
          position={[-0.7074, 3.9487, 1.0911]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.0013, -0.0015, -0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC3BG13001.geometry}
          position={[0.6449, 0.8179, 1.2363]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC4BG06001.geometry}
          position={[1.1923, 1.4819, 1.4708]}
          scale={[0.0012, 0.0014, 0.0013]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC7BG10001.geometry}
          position={[0.7101, 0.35, 0.5259]}
          rotation={[0, 1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0017]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC9BG19001.geometry}
          position={[-1.0338, 1.2742, 0.7945]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0013, 0.0014, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC9BG19Blinds001.geometry}
          position={[-0.7115, 0.9238, 0.935]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-0.0013, -0.0015, -0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object01001.geometry}
          position={[-1.0338, 1.2742, 0.7953]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
      </mesh>
      <mesh material={materials['default']} geometry={nodes.Plane.geometry} position={[-1.86, 0, 2.42]}>
        <mesh
          material={materials['default']}
          geometry={nodes.B_court_fence.geometry}
          position={[0.625, 0.4479, -0.5098]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.B_court_lights.geometry}
          position={[0.625, 0.4479, -0.5098]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Basketball_court.geometry}
          position={[0.625, 0.4479, -0.5098]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.BG27bC1.geometry}
          position={[1.2956, 1.0182, -1.7525]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block4.geometry}
          position={[6.4037, 0.4437, -0.125]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block4_details.geometry}
          position={[-2.4123, 0.4437, -0.8906]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block_4_Trees.geometry}
          position={[4.3984, 0.4198, 8.5905]}
          scale={[0.0536, 0.0666, 0.0536]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassBG27C1.geometry}
          position={[0.8956, 1.023, -2.2342]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC2BG20.geometry}
          position={[2.116, 1.0973, -1.9033]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0016, 0.0016, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC5BG21.geometry}
          position={[-2.1214, 2.4863, -1.8518]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0023, 0.0017, 0.0016]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC6BG16.geometry}
          position={[0.4843, 2.951, 1.6028]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC7BG17.geometry}
          position={[-1.2998, 0.6586, 1.4628]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC8BG06.geometry}
          position={[1.5081, 0.8391, 1.2477]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC9BG03.geometry}
          position={[-0.3282, 0.6069, -2.1484]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC9BG21.geometry}
          position={[1.8681, 1.0407, -1.436]}
          rotation={[1.5705, 0, Math.PI]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.glassSolar_panels.geometry}
          position={[1.6499, 1.6575, -1.8623]}
          rotation={[Math.PI / 2, 1.3156, -Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC2BG20.geometry}
          position={[1.8048, 0.9748, -1.9382]}
          rotation={[Math.PI, -1.5705, 0]}
          scale={[-0.0016, -0.0015, -0.0016]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC5BG21.geometry}
          position={[-1.9046, 0.6581, -2.2849]}
          scale={[0.0017, 0.0016, 0.0017]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC6BG16.geometry}
          position={[0.1174, 0.6313, 2.249]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC8BG06.geometry}
          position={[1.4961, 0.6236, 1.6351]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC8BG06_detail.geometry}
          position={[1.4961, 0.6236, 1.6351]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC9BG03.geometry}
          position={[0.6626, 0.6069, -1.5654]}
          rotation={[0, 1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC9BG21.geometry}
          position={[1.7484, 0.6121, -1.0867]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.0015, -0.0014, -0.0015]}
        />
      </mesh>
      <mesh
        material={materials['default']}
        geometry={nodes.Plane003.geometry}
        position={[3.9287, 0, -3.6022]}
        rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          material={materials['default']}
          geometry={nodes.B_court_fence001.geometry}
          position={[0.625, 0.4479, -0.5098]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.B_court_lights001.geometry}
          position={[0.625, 0.4479, -0.5098]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Basketball_court001.geometry}
          position={[0.625, 0.4479, -0.5098]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.BG27bC1001.geometry}
          position={[1.2956, 1.0182, -1.7525]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block4001.geometry}
          position={[6.4037, 0.4437, -0.125]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block4_details001.geometry}
          position={[-2.4123, 0.4437, -0.8906]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Block_4_Trees001.geometry}
          position={[4.3984, 0.4198, 8.5905]}
          scale={[0.0536, 0.0666, 0.0536]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassBG27C1001.geometry}
          position={[0.8956, 1.023, -2.2342]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC2BG20001.geometry}
          position={[2.116, 1.0973, -1.9033]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0016, 0.0016, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC5BG21001.geometry}
          position={[-2.1214, 2.4863, -1.8518]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0023, 0.0017, 0.0016]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC7BG17001.geometry}
          position={[-1.2998, 0.6586, 1.4628]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC8BG06001.geometry}
          position={[1.5081, 0.8391, 1.2476]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC9BG03001.geometry}
          position={[-0.3282, 0.6069, -2.1484]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC9BG21001.geometry}
          position={[1.8681, 1.0407, -1.436]}
          rotation={[1.5705, 0, Math.PI]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.glassSolar_panels001.geometry}
          position={[1.6499, 1.6575, -1.8623]}
          rotation={[Math.PI / 2, 1.3156, -Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC2BG20001.geometry}
          position={[1.8048, 0.9748, -1.9382]}
          rotation={[Math.PI, -1.5705, 0]}
          scale={[-0.0016, -0.0015, -0.0016]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC5BG21001.geometry}
          position={[-1.9046, 0.6581, -2.2849]}
          scale={[0.0017, 0.0016, 0.0017]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC8BG06001.geometry}
          position={[1.4961, 0.6236, 1.6351]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC8BG06_detail001.geometry}
          position={[1.4961, 0.6236, 1.6351]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC9BG03001.geometry}
          position={[0.6626, 0.6069, -1.5654]}
          rotation={[0, 1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.KC9BG21001.geometry}
          position={[1.7484, 0.6121, -1.0867]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.0015, -0.0014, -0.0015]}
        />
      </mesh>
      <mesh
        material={materials['default']}
        geometry={nodes.Plane004.geometry}
        position={[-0.26, 0.4, -4.66]}
        rotation={[0, 1.5464, 0]}
        scale={[0.06, 0.06, 0.06]}>
        <mesh
          material={materials['default']}
          geometry={nodes['3'].geometry}
          position={[-18.5665, 5.1, -0.6424]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0087, 0.0087, 0.0087]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box012.geometry}
          position={[-1.4551, 3.3504, -14.0661]}
          rotation={[0, 1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box031.geometry}
          position={[-1.7398, 1.0837, -13.1892]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box033.geometry}
          position={[-3.6955, 1.0837, -13.1892]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box053.geometry}
          position={[3.3767, 1.1959, -11.9621]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box054.geometry}
          position={[4.0848, 1.2584, -11.1626]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box055.geometry}
          position={[3.8273, 1.5834, -11.1778]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box056.geometry}
          position={[4.0848, 1.5993, -11.1626]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box062.geometry}
          position={[-0.2872, 2.0936, -11.3638]}
          scale={[0.0145, 0.01, 0.0145]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box065.geometry}
          position={[-1.8629, 2.6668, -12.5325]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box075.geometry}
          position={[-0.1063, 1.5846, -11.2804]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.0108, 0.0152, 0.0173]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box083.geometry}
          position={[-0.3557, 1.3327, -11.7215]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.0173, 0.0173, 0.0173]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box088.geometry}
          position={[-5.6389, 2.4349, -10.2625]}
          rotation={[0, 1.5705, 0]}
          scale={[0.0112, 0.0107, 0.0107]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box089.geometry}
          position={[1.363, 2.0936, -11.3696]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.0145, 0.01, 0.0145]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box090.geometry}
          position={[1.1821, 1.5846, -11.4531]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={[0.0108, 0.0152, 0.0173]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box091.geometry}
          position={[1.4315, 1.3327, -11.012]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={[0.0173, 0.0173, 0.0173]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box095.geometry}
          position={[-0.4042, 1.1152, -13.4588]}
          scale={[0.0089, 0.0089, 0.0089]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box150.geometry}
          position={[4.0201, 5.2458, -12.6835]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box151.geometry}
          position={[4.0201, 5.192, -10.6723]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box152.geometry}
          position={[4.0201, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box153.geometry}
          position={[2.0185, 5.2458, -12.6835]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box154.geometry}
          position={[2.0185, 5.192, -10.6723]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box155.geometry}
          position={[2.0185, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box156.geometry}
          position={[-0.0108, 5.2458, -12.6835]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box157.geometry}
          position={[-0.0108, 5.192, -10.6723]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box158.geometry}
          position={[-0.0108, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box159.geometry}
          position={[-2.011, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box160.geometry}
          position={[-4.0105, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box162.geometry}
          position={[-2.868, 2.381, -11.4789]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0082, 0.0082, 0.0082]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Box163.geometry}
          position={[-3.9543, 2.381, -11.4789]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0082, 0.0082, 0.0082]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.carwash.geometry}
          position={[11.7435, 5.0715, -10.3245]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.carwash_icon.geometry}
          position={[11.7435, 6.4715, -7.4337]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.ChamferBox005.geometry}
          position={[3.0498, 1.1811, -11.0212]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Circle001.geometry}
          position={[-6.4368, 5.74, -1.5349]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Circle002.geometry}
          position={[-7.6159, 1.14, -0.9995]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Circle003.geometry}
          position={[-7.6159, 1.14, 4.5298]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Circle004.geometry}
          position={[5.2982, 1.14, 4.5297]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Circle005.geometry}
          position={[5.2982, 1.14, -0.9996]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube.geometry}
          position={[6.0364, 2.6827, -13.5124]}
          rotation={[-Math.PI / 2, 0, -0.356]}
          scale={[-0.052, -0.4, -0.7332]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube002.geometry}
          position={[6.0846, 2.67, -6.6496]}
          rotation={[-3.1367, -0.5636, 3.1409]}
          scale={[0.4153, 0.7383, 0.0954]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube003.geometry}
          position={[3.9859, 3.07, 4.7165]}
          rotation={[0.1434, 0, 0]}
          scale={[0.3945, 0.223, 0.0448]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube004.geometry}
          position={[6.3152, 2.6827, -14.2621]}
          rotation={[-Math.PI / 2, 0, -0.356]}
          scale={[-0.052, -0.4, -0.7332]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube005.geometry}
          position={[5.7566, 2.6827, -12.7602]}
          rotation={[-Math.PI / 2, 0, -0.356]}
          scale={[-0.052, -0.4, -0.7332]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube006.geometry}
          position={[-1.5675, 2.808, -10.772]}
          scale={[7.08, 1.7, 3.02]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube007.geometry}
          position={[3.9859, 3.07, 4.3565]}
          rotation={[0.7696, 0.3074, 1.681]}
          scale={[0.353, 0.4368, 0.0448]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube010.geometry}
          position={[3.0074, 2.2559, -12.0815]}
          rotation={[0, 0, -Math.PI / 6]}
          scale={[0.0173, 0.1848, 0.104]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube014.geometry}
          position={[2.1224, 3.1216, -13.6401]}
          rotation={[0.0873, 1.5708, 0]}
          scale={[0.0701, 0.6306, 1.121]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube015.geometry}
          position={[5.0423, 3.1216, -10.2933]}
          scale={[0.0701, 0.6306, 1.121]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube016.geometry}
          position={[-3.8093, 1.937, -9.7346]}
          rotation={[Math.PI, 0.003, 2.5656]}
          scale={[0.02, 0.2057, 0.1157]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube017.geometry}
          position={[-3.8293, 1.4903, -9.7346]}
          rotation={[-Math.PI, 0.003, -Math.PI]}
          scale={[0.1, 0.4, 0.08]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube018.geometry}
          position={[-5.1592, 3.442, -10.8416]}
          scale={[0.0398, 0.3579, 0.6362]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube019.geometry}
          position={[-5.1592, 3.442, -9.5816]}
          scale={[0.0398, 0.3579, 0.6362]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube020.geometry}
          position={[-5.1592, 3.442, -8.3216]}
          scale={[0.0398, 0.3579, 0.6362]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_009.geometry}
          position={[0.1218, 1.3221, -11.2549]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_010.geometry}
          position={[0.1218, 1.3221, -11.4346]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_011.geometry}
          position={[0.0428, 1.3221, -11.2549]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_012.geometry}
          position={[0.0428, 1.3221, -11.4346]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_013.geometry}
          position={[-0.0347, 1.3221, -11.2549]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_014.geometry}
          position={[-0.0347, 1.3221, -11.4346]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_015.geometry}
          position={[-0.1066, 1.3221, -11.2549]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_016.geometry}
          position={[-0.1066, 1.3221, -11.4346]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_017.geometry}
          position={[0.954, 1.3221, -11.4786]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_018.geometry}
          position={[0.954, 1.3221, -11.2989]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_019.geometry}
          position={[1.033, 1.3221, -11.4786]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_020.geometry}
          position={[1.033, 1.3221, -11.2989]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_021.geometry}
          position={[1.1105, 1.3221, -11.4786]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_022.geometry}
          position={[1.1105, 1.3221, -11.2989]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_023.geometry}
          position={[1.1824, 1.3221, -11.4786]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_3_024.geometry}
          position={[1.1824, 1.3221, -11.2989]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_7_010.geometry}
          position={[0.0172, 1.3117, -11.0776]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_7_011.geometry}
          position={[1.0586, 1.3117, -11.6559]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_7_012.geometry}
          position={[0.9737, 1.3117, -11.6559]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_7_013.geometry}
          position={[1.0159, 1.3132, -11.7756]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_7_3.geometry}
          position={[0.1021, 1.3117, -11.0776]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_7_9.geometry}
          position={[0.0599, 1.3132, -10.9579]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_015.geometry}
          position={[-0.3126, 1.3247, -10.9408]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_016.geometry}
          position={[-0.3126, 1.3247, -10.9957]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_019.geometry}
          position={[-0.1271, 1.3247, -11.0567]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_020.geometry}
          position={[-0.3126, 1.3247, -11.1124]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_022.geometry}
          position={[1.3884, 1.3247, -11.7926]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_024.geometry}
          position={[1.2029, 1.3247, -11.7378]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_025.geometry}
          position={[1.3884, 1.3247, -11.6768]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_026.geometry}
          position={[1.2029, 1.3247, -11.6768]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.cutie_8_14.geometry}
          position={[-0.1271, 1.3247, -10.9408]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0061, 0.0061, 0.0061]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder.geometry}
          position={[3.0474, 2.1559, -12.1215]}
          scale={[0.02, 0.16, 0.02]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder005.geometry}
          position={[2.0441, 1.1019, -9.1454]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder007.geometry}
          position={[2.6701, 1.6117, -9.1456]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder009.geometry}
          position={[3.3146, 1.1019, -9.1454]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder010.geometry}
          position={[4.6203, 1.1019, -9.1454]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder011.geometry}
          position={[4.6438, 1.6117, -9.1456]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder012.geometry}
          position={[5.2883, 1.1019, -9.1454]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder015.geometry}
          position={[2.0252, 1.6117, -9.1456]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder016.geometry}
          position={[1.3807, 1.1019, -9.1454]}
          rotation={[Math.PI, -1.5705, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder025.geometry}
          position={[-0.2983, 1.8048, -11.1355]}
          scale={[0.0011, 0.0011, 0.0011]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder027.geometry}
          position={[-0.0605, 2.1103, -11.3265]}
          scale={[0.0111, 0.0111, 0.0111]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder028.geometry}
          position={[1.3741, 1.8048, -11.5979]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.0011, 0.0011, 0.0011]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cylinder029.geometry}
          position={[1.1363, 2.1103, -11.4069]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.0111, 0.0111, 0.0111]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.door_frame_int001001.geometry}
          position={[0.5404, 0.3801, -12.3509]}
          rotation={[0, 1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.FixedWindow010.geometry}
          position={[-0.3871, 1.365, -13.1862]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.0089, 0.0089, 0.0089]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.gaspump002.geometry}
          position={[3.977, 1.14, 4.5297]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.gaspump003.geometry}
          position={[3.977, 1.14, -0.9996]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.greeting_card_002.geometry}
          position={[-1.746, 1.4755, -11.1472]}
          rotation={[-Math.PI / 2, 1.4835, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.greeting_card_003.geometry}
          position={[-2.0725, 1.4755, -11.2571]}
          rotation={[-3.0543, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.greeting_card_004.geometry}
          position={[-2.1823, 1.4755, -10.9324]}
          rotation={[-Math.PI / 2, -1.4835, -Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.greeting_card_01.geometry}
          position={[-1.8588, 1.4755, -10.8215]}
          rotation={[-0.0873, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Kent_mentol_4.geometry}
          position={[5.2611, 1.8443, -12.1377]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Line001.geometry}
          position={[-1.5897, 5.2344, -10.6107]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Line002.geometry}
          position={[14.8841, 5.2344, -2.3011]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Line029.geometry}
          position={[-4.9026, 1.6729, -10.1567]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.market.geometry}
          position={[0.2287, 20.5737, -7.4686]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.market_icon.geometry}
          position={[-19.8802, 5.6781, -7.4686]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object027.geometry}
          position={[3.3767, 1.1959, -11.9621]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object028.geometry}
          position={[3.3767, 1.1959, -11.9621]}
          rotation={[Math.PI, 1.5705, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object029001.geometry}
          position={[3.2354, 2.1979, -11.6767]}
          rotation={[Math.PI / 2, -1.1345, -Math.PI / 2]}
          scale={[-0.0117, -0.0117, -0.0085]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object030001.geometry}
          position={[-1.8098, 2.6668, -12.5325]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0054, 0.0054, 0.0054]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object031.geometry}
          position={[5.807, 2.0379, -12.8763]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0081, 0.0081, 0.0081]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object057.geometry}
          position={[-4.3966, 2.3402, -13.767]}
          rotation={[0, 1.5705, 0]}
          scale={[0.0082, 0.0082, 0.0082]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object057001.geometry}
          position={[-2.868, 2.381, -11.4789]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0082, 0.0082, 0.0082]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object058.geometry}
          position={[-4.8229, 3.0202, -7.767]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0082, 0.0082, 0.0082]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object058001.geometry}
          position={[-3.9543, 2.381, -11.4789]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0082, 0.0082, 0.0082]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object065.geometry}
          position={[-1.5676, 0.9585, -1.2862]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.0121, 0.0121, 0.0121]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object066.geometry}
          position={[8.8792, 0.9585, -6.8217]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0121, 0.0121, 0.0121]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object067.geometry}
          position={[10.5751, 0.9205, 16.3191]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.0121, 0.0121, 0.0121]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object068.geometry}
          position={[14.0191, 1.08, -4.2776]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object070.geometry}
          position={[14.0191, 1.08, -18.8464]}
          rotation={[Math.PI, 0, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object071.geometry}
          position={[-6.4368, 5.74, -1.5349]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object072.geometry}
          position={[21.0266, 4.3587, -6.3414]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object073.geometry}
          position={[-6.895, 5.7187, -16.7606]}
          rotation={[0.1536, -Math.PI / 2, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.order_menu.geometry}
          position={[5.9, 1.58, -13.58]}
          rotation={[Math.PI / 2, 0, 0.356]}
          scale={[0.02, 0.01, 0.02]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Plane003_1.geometry}
          position={[-0.5313, 2.4685, -7.5294]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Plane016.geometry}
          position={[-8.5727, 3.9356, -10.8352]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0078, 0.0063, 0.007]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.portrait_promotional_stand.geometry}
          position={[5.94, 1.58, -6.8]}
          rotation={[Math.PI / 2, 0, 1.0018]}
          scale={[0.02, 0.01, 0.02]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle001.geometry}
          position={[2.1286, 1.8455, -8.8666]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle002.geometry}
          position={[-18.1297, 5.28, -11.5342]}
          rotation={[0, -1.5705, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle003.geometry}
          position={[-6.2834, 1.04, -0.9995]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle004.geometry}
          position={[2.6661, 1.9884, -9.1454]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.0078, -0.0078, -0.0078]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle005.geometry}
          position={[2.6516, 1.9884, -9.16]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.0078, -0.0078, -0.0078]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle006.geometry}
          position={[11.2666, 1.28, -7.3554]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle006001.geometry}
          position={[3.6392, 1.841, -9.1454]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle007001.geometry}
          position={[4.3017, 1.841, -9.1454]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle132.geometry}
          position={[-6.9721, 5.7349, -2.7578]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle135.geometry}
          position={[-6.6557, 4.68, -7.5]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle137.geometry}
          position={[-1.5962, 1.08, -10.4045]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle140.geometry}
          position={[14.3412, 4.68, -9.4243]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle142.geometry}
          position={[-6.2295, 3.8214, -13.8365]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle143.geometry}
          position={[-0.0822, 3.8214, -13.8565]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle144.geometry}
          position={[-1.1368, 5.7349, -2.7578]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle145.geometry}
          position={[4.6985, 5.7349, -2.7578]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle146.geometry}
          position={[-6.9721, 5.7349, 1.7651]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle147.geometry}
          position={[-1.1368, 5.7349, 1.7651]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle148.geometry}
          position={[4.6985, 5.7349, 1.7651]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle149.geometry}
          position={[-6.9721, 5.7349, 6.288]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle150.geometry}
          position={[-1.1368, 5.7349, 6.288]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle151.geometry}
          position={[4.6985, 5.7349, 6.288]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle153.geometry}
          position={[-1.1368, 1.08, 1.7651]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle156.geometry}
          position={[-6.2834, 1.04, 4.5298]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle157.geometry}
          position={[1.356, 1.54, 4.5297]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle158.geometry}
          position={[2.4375, 1.1386, 4.5297]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle159.geometry}
          position={[3.9657, 1.04, 4.5297]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle160.geometry}
          position={[1.356, 1.54, -0.9996]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle161.geometry}
          position={[2.6775, 1.1386, -0.9996]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Rectangle162.geometry}
          position={[3.9657, 1.04, -0.9996]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.screen011001.geometry}
          position={[3.2354, 2.1979, -11.6767]}
          rotation={[Math.PI / 2, -1.1345, -Math.PI / 2]}
          scale={[-0.0117, -0.0117, -0.0085]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.screws.geometry}
          position={[-1.9652, 1.1365, -11.0398]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Shape001.geometry}
          position={[-1.5962, 1.08, -10.4045]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Shape002.geometry}
          position={[-1.1368, 1.08, 1.7651]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Shape1.geometry}
          position={[-7.7988, 4.4933, 7.7627]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.speaker_box.geometry}
          position={[6.1933, 1.5157, -13.4745]}
          rotation={[Math.PI / 2, 0, 0.356]}
          scale={[0.0724, 0.0938, 0.4688]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Sphere.geometry}
          position={[6.2071, 1.837, -13.4694]}
          rotation={[Math.PI / 2, 0, 0.356]}
          scale={[0.0767, 0.0807, 0.075]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.support_bar.geometry}
          position={[-1.9652, 1.1365, -11.0398]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Text.geometry}
          position={[6.2609, 1.8932, -13.4354]}
          rotation={[Math.PI / 2, 0, -1.2147]}
          scale={[0.0938, 0.0724, 0.1031]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Top_stand.geometry}
          position={[4.0059, 2.83, 4.5365]}
          scale={[0.38, 0.1, 0.14]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.vorota002.geometry}
          position={[25.0899, 1.0459, 37.2974]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0093, 0.0094, 0.0093]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.vorota003.geometry}
          position={[25.0899, 1.0459, 42.8973]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0093, 0.0094, 0.0093]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.vorota01.geometry}
          position={[25.0899, 1.0459, 31.6974]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0093, 0.0094, 0.0093]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.wheels002.geometry}
          position={[-0.7262, 1.1381, -11.8138]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.022, 0.0264, 0.022]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.wheels006.geometry}
          position={[1.802, 1.1381, -10.9197]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.022, 0.0264, 0.022]}
        />
      </mesh>
      <mesh
        material={materials['default']}
        geometry={nodes.GlassKC4BG06002.geometry}
        position={[3.2072, 1.1719, -5.2661]}
        rotation={[Math.PI / 2, 0, 1.6054]}
        scale={[0.0008, 0.0013, 0.0014]}
      />
      <mesh
        material={materials['default']}
        geometry={nodes.KC4BG06002.geometry}
        position={[3.622, 1.5592, -5.2557]}
        rotation={[Math.PI, -1.5362, Math.PI]}
        scale={[0.0008, 0.0014, 0.0013]}
      />
    </group>
  )
}

useGLTF.preload('/dnsc.glb')
