/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture , Plane , Sphere } from '@react-three/drei'
import dscf from './dscf.glb'
import folia from './folia.png'
import folic from './folic.png'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(dscf)

  for (const property in materials) {
    materials[property].metalness = 0.1;
    materials[property].roughness = 0.5;
    //console.log(materials[property].metalness);
  }
  materials.Foliage.transparent = true;
  materials.Foliage.alphaMap = useTexture(folia);
  materials.Foliage.map = useTexture(folic);
  materials.orange.color.set("#3F2612");
  //materials['_22_-_Default']
  //console.log(materials);
  return (<>
   <Plane visible={props.church3} material={materials['_22_-_Default']}  rotation={[-Math.PI*0.5,0,0]} position={[5.9,0.51,-3.5]} args={[1.1,4]} />
    <group  position={props.position} rotation={props.rotation} ref={group} {...props} dispose={null}>
     
      <mesh material={materials['default']} geometry={nodes.Plane001.geometry} position={[4.0708, 0.1, 2.5311]}>
        <group visible={false} position={[-0.9901, 0.5276, -1.557]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4323.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4323_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4323_2.geometry} />
          <mesh material={materials.ggrey} geometry={nodes.ID4323_3.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4323_4.geometry} />
          <mesh
            material={materials.Material__21124}
            geometry={nodes.BG10C1Glass.geometry}
            position={[224.8511, 62.3783, 250.96]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
        </group>
        <group
          position={[-1.2658, 0.3195, -12.9022]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0536, 0.0666, 0.0536]}>
          <mesh material={materials.bark} geometry={nodes.ID4314.geometry} />
          <mesh material={materials.Foliage} geometry={nodes.ID4314_1.geometry} />
          <mesh material={materials.bark2} geometry={nodes.ID4314_2.geometry} />
          <mesh material={materials['Cypress plant']} geometry={nodes.ID4314_3.geometry} />
          <mesh material={materials.bark} geometry={nodes.ID4314_4.geometry} />
          <mesh material={materials['Cypress plant']} geometry={nodes.ID4314_5.geometry} />
        </group>
        <group position={[0.6385, 0.3437, -2.6553]} rotation={[Math.PI, 1.5705, 0]} scale={[-0.0015, -0.0015, -0.0015]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4305.geometry} />
          <mesh material={materials.fire} geometry={nodes.ID4305_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4305_2.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4305_3.geometry} />
          <mesh material={materials.fire} geometry={nodes.ID4305_4.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4305_5.geometry} />
          <mesh material={materials.fire} geometry={nodes.ID4305_6.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4305_7.geometry} />
          <mesh material={materials.green} geometry={nodes.ID4305_8.geometry} />
        </group>
        <group position={[-6.5474, 0.3437, -0.2367]} rotation={[0, 0, -Math.PI]} scale={[-0.0015, -0.0015, -0.0015]}>
          <mesh material={materials['_08_-_Default.058']} geometry={nodes.ID4296.geometry} />
          <mesh material={materials['_08_-_Default.060']} geometry={nodes.ID4296_1.geometry} />
          <mesh material={materials['_01_-_Default.153']} geometry={nodes.ID4296_2.geometry} />
          <mesh material={materials['_02_-_Default.099']} geometry={nodes.ID4296_3.geometry} />
          <mesh material={materials['_01_-_Default.150']} geometry={nodes.ID4296_4.geometry} />
          <mesh material={materials['_03_-_Default.067']} geometry={nodes.ID4296_5.geometry} />
          <mesh material={materials['_08_-_Default.057']} geometry={nodes.ID4296_6.geometry} />
          <mesh material={materials['_03_-_Default.070']} geometry={nodes.ID4296_7.geometry} />
          <mesh material={materials['_07_-_Default.058']} geometry={nodes.ID4296_8.geometry} />
          <mesh material={materials.green} geometry={nodes.ID4296_9.geometry} />
          <mesh material={materials['_01_-_Default.152']} geometry={nodes.ID4296_10.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4296_11.geometry} />
          <mesh material={materials.Material__2487} geometry={nodes.ID4296_12.geometry} />
          <mesh material={materials['_08_-_Default.059']} geometry={nodes.ID4296_13.geometry} />
          <mesh material={materials['_03_-_Default.068']} geometry={nodes.ID4296_14.geometry} />
          <mesh material={materials['_03_-_Default.069']} geometry={nodes.ID4296_15.geometry} />
          <mesh material={materials['_09_-_Default.044']} geometry={nodes.ID4296_16.geometry} />
          <mesh material={materials['_14_-_Default.042']} geometry={nodes.ID4296_17.geometry} />
          <mesh material={materials['_15_-_Default.032']} geometry={nodes.ID4296_18.geometry} />
          <mesh material={materials['_02_-_Default.100']} geometry={nodes.ID4296_19.geometry} />
          <mesh material={materials['_07_-_Default.057']} geometry={nodes.ID4296_20.geometry} />
          <mesh material={materials['_03_-_Default.066']} geometry={nodes.ID4296_21.geometry} />
          <mesh material={materials['_02_-_Default.101']} geometry={nodes.ID4296_22.geometry} />
          <mesh material={materials['_21_-_Default']} geometry={nodes.ID4296_23.geometry} />
          <mesh material={materials['_08_-_Default.062']} geometry={nodes.ID4296_24.geometry} />
          <mesh material={materials['_02_-_Default.102']} geometry={nodes.ID4296_25.geometry} />
          <mesh material={materials['_08_-_Default.061']} geometry={nodes.ID4296_26.geometry} />
          <mesh material={materials['_01_-_Default.154']} geometry={nodes.ID4296_27.geometry} />
          <mesh material={materials['_02_-_Default.103']} geometry={nodes.ID4296_28.geometry} />
          <mesh material={materials['_01_-_Default.155']} geometry={nodes.ID4296_29.geometry} />
          <mesh material={materials['_22_-_Default']} geometry={nodes.ID4296_30.geometry} />
          <mesh material={materials['_03_-_Default.071']} geometry={nodes.ID4296_31.geometry} />
          <mesh material={materials['_01_-_Default.156']} geometry={nodes.ID4296_32.geometry} />
          <mesh material={materials['_03_-_Default.072']} geometry={nodes.ID4296_33.geometry} />
          <mesh material={materials['_13_-_Default.033']} geometry={nodes.ID4296_34.geometry} />
          <mesh material={materials['_20_-_Default.006']} geometry={nodes.ID4296_35.geometry} />
          <mesh material={materials['_16_-_Default']} geometry={nodes.ID4296_36.geometry} />
          <mesh material={materials['_21_-_Default.007']} geometry={nodes.ID4296_37.geometry} />
          <mesh material={materials['_15_-_Default.033']} geometry={nodes.ID4296_38.geometry} />
          <mesh material={materials['_13_-_Default.034']} geometry={nodes.ID4296_39.geometry} />
        </group>
        {/*
        <mesh visible={false}
          material={materials.Mat}
          geometry={nodes.Glass2KC9BG19.geometry}
          position={[-1.2258, 0.4376, 1.1666]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />*/}
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassKC3BG13.geometry}
          position={[1.5239, 0.7964, 0.5079]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials.Glass18reflection}
          geometry={nodes.GlassKC4BG06.geometry}
          position={[1.1962, 1.0946, 1.8857]}
          rotation={[1.5708, 0, 0]}
          scale={[0.0012, 0.0013, 0.0014]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.GlassKC4BG16.geometry}
          position={[1.2091, 0.4447, -2.3386]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0014, -0.0015]}
        />
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassKC7BG10.geometry}
          position={[1.4273, 0.7056, -0.068]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0015, 0.0017, 0.0015]}
        />
        {/*}
        <mesh visible={false}
          material={materials.Glass80eflection}
          geometry={nodes.GlassKC9BG19.geometry}
          position={[-0.7074, 3.9487, 1.0911]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.0013, -0.0015, -0.0014]}
  />*/}
        <group position={[0.6449, 0.8179, 1.2363]} rotation={[Math.PI, 1.5705, 0]} scale={[-0.0015, -0.0015, -0.0015]}>
          <mesh material={materials.brick} geometry={nodes.ID4359.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4359_1.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4359_2.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4359_3.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4359_4.geometry} />
        </group>
        <group  position={[1.1923, 1.4819, 1.4708]} scale={[0.0012, 0.0014, 0.0013]}>
          <mesh material={materials.brick} geometry={nodes.ID3693.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID3693_1.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID3693_2.geometry} />
          <mesh material={materials.white} geometry={nodes.ID3693_3.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID3693_4.geometry} />
        </group>
        <group position={[1.025, 0.7741, -1.4953]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0015, 0.0015, 0.0014]}>
          <mesh material={materials.brick} geometry={nodes.ID4341.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4341_1.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4341_2.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4341_3.geometry} />
        </group>
        <group position={[0.7101, 0.35, 0.5259]} rotation={[0, 1.5705, 0]} scale={[0.0015, 0.0015, 0.0017]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4386.geometry} />
          <mesh material={materials.ggrey} geometry={nodes.ID4386_1.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4386_2.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4386_3.geometry} />
        </group>
        {/*
        <group visible={false} position={[-1.0338, 1.2742, 0.7945]} rotation={[0, -1.5705, 0]} scale={[0.0013, 0.0014, 0.0015]}>
          <mesh material={materials.brick} geometry={nodes.ID4431.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4431_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4431_2.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4431_3.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4431_4.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4431_5.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4431_6.geometry} />
        </group>
        <mesh visible={false}
          material={materials['_20_-_Default.009']}
          geometry={nodes.KC9BG19Blinds.geometry}
          position={[-0.7115, 0.9238, 0.935]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-0.0013, -0.0015, -0.0014]}
        />
        <group visible={false} position={[-1.0338, 1.2742, 0.7953]} rotation={[0, -1.5705, 0]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4467.geometry} />
          <mesh material={materials.red} geometry={nodes.ID4467_1.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4467_2.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4467_3.geometry} />
        </group>*/}
      </mesh>
      <mesh material={materials['default']} geometry={nodes.Plane002.geometry} position={[-1.7, 0.1, -3.24]}>
        {/*<group visible={false} position={[-0.9901, 0.5276, -1.557]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4323.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4323_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4323_2.geometry} />
          <mesh material={materials.ggrey} geometry={nodes.ID4323_3.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4323_4.geometry} />
          <mesh
            material={materials.Material__21124}
            geometry={nodes.BG10C1Glass001.geometry}
            position={[224.8507, 62.3783, 250.9597]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
      </group>*/}
        <group
          position={[-1.2658, 0.3195, -12.5622]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0536, 0.0666, 0.0536]}>
          <mesh material={materials.bark} geometry={nodes.ID4314.geometry} />
          <mesh material={materials.Foliage} geometry={nodes.ID4314_1.geometry} />
          <mesh material={materials.bark2} geometry={nodes.ID4314_2.geometry} />
          <mesh material={materials['Cypress plant']} geometry={nodes.ID4314_3.geometry} />
          <mesh material={materials.bark} geometry={nodes.ID4314_4.geometry} />
          <mesh material={materials['Cypress plant']} geometry={nodes.ID4314_5.geometry} />
        </group>
        <group position={[0.6385, 0.3437, -2.6553]} rotation={[Math.PI, 1.5705, 0]} scale={[-0.0015, -0.0015, -0.0015]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4305.geometry} />
          <mesh material={materials.fire} geometry={nodes.ID4305_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4305_2.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4305_3.geometry} />
          <mesh material={materials.fire} geometry={nodes.ID4305_4.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4305_5.geometry} />
          <mesh material={materials.fire} geometry={nodes.ID4305_6.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4305_7.geometry} />
          <mesh material={materials.green} geometry={nodes.ID4305_8.geometry} />
        </group>
        <group position={[-6.5474, 0.3437, -0.2367]} rotation={[0, 0, -Math.PI]} scale={[-0.0015, -0.0015, -0.0015]}>
          <mesh material={materials['_08_-_Default.058']} geometry={nodes.ID4296.geometry} />
          <mesh material={materials['_08_-_Default.060']} geometry={nodes.ID4296_1.geometry} />
          <mesh material={materials['_01_-_Default.153']} geometry={nodes.ID4296_2.geometry} />
          <mesh material={materials['_02_-_Default.099']} geometry={nodes.ID4296_3.geometry} />
          <mesh material={materials['_01_-_Default.150']} geometry={nodes.ID4296_4.geometry} />
          <mesh material={materials['_03_-_Default.067']} geometry={nodes.ID4296_5.geometry} />
          <mesh material={materials['_08_-_Default.057']} geometry={nodes.ID4296_6.geometry} />
          <mesh material={materials['_03_-_Default.070']} geometry={nodes.ID4296_7.geometry} />
          <mesh material={materials['_07_-_Default.058']} geometry={nodes.ID4296_8.geometry} />
          <mesh material={materials.green} geometry={nodes.ID4296_9.geometry} />
          <mesh material={materials['_01_-_Default.152']} geometry={nodes.ID4296_10.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4296_11.geometry} />
          <mesh material={materials.Material__2487} geometry={nodes.ID4296_12.geometry} />
          <mesh material={materials['_08_-_Default.059']} geometry={nodes.ID4296_13.geometry} />
          <mesh material={materials['_03_-_Default.068']} geometry={nodes.ID4296_14.geometry} />
          <mesh material={materials['_03_-_Default.069']} geometry={nodes.ID4296_15.geometry} />
          <mesh material={materials['_09_-_Default.044']} geometry={nodes.ID4296_16.geometry} />
          <mesh material={materials['_14_-_Default.042']} geometry={nodes.ID4296_17.geometry} />
          <mesh material={materials['_15_-_Default.032']} geometry={nodes.ID4296_18.geometry} />
          <mesh material={materials['_02_-_Default.100']} geometry={nodes.ID4296_19.geometry} />
          <mesh material={materials['_07_-_Default.057']} geometry={nodes.ID4296_20.geometry} />
          <mesh material={materials['_03_-_Default.066']} geometry={nodes.ID4296_21.geometry} />
          <mesh material={materials['_02_-_Default.101']} geometry={nodes.ID4296_22.geometry} />
          <mesh material={materials['_21_-_Default']} geometry={nodes.ID4296_23.geometry} />
          <mesh material={materials['_08_-_Default.062']} geometry={nodes.ID4296_24.geometry} />
          <mesh material={materials['_02_-_Default.102']} geometry={nodes.ID4296_25.geometry} />
          <mesh material={materials['_08_-_Default.061']} geometry={nodes.ID4296_26.geometry} />
          <mesh material={materials['_01_-_Default.154']} geometry={nodes.ID4296_27.geometry} />
          <mesh material={materials['_02_-_Default.103']} geometry={nodes.ID4296_28.geometry} />
          <mesh material={materials['_01_-_Default.155']} geometry={nodes.ID4296_29.geometry} />
          <mesh material={materials['_22_-_Default']} geometry={nodes.ID4296_30.geometry} />
          <mesh material={materials['_03_-_Default.071']} geometry={nodes.ID4296_31.geometry} />
          <mesh material={materials['_01_-_Default.156']} geometry={nodes.ID4296_32.geometry} />
          <mesh material={materials['_03_-_Default.072']} geometry={nodes.ID4296_33.geometry} />
          <mesh material={materials['_13_-_Default.033']} geometry={nodes.ID4296_34.geometry} />
          <mesh material={materials['_20_-_Default.006']} geometry={nodes.ID4296_35.geometry} />
          <mesh material={materials['_16_-_Default']} geometry={nodes.ID4296_36.geometry} />
          <mesh material={materials['_21_-_Default.007']} geometry={nodes.ID4296_37.geometry} />
          <mesh material={materials['_15_-_Default.033']} geometry={nodes.ID4296_38.geometry} />
          <mesh material={materials['_13_-_Default.034']} geometry={nodes.ID4296_39.geometry} />
        </group>
        <mesh
          material={materials.Mat}
          geometry={nodes.Glass2KC9BG19001.geometry}
          position={[-1.2258, 0.4376, 1.1666]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        {/*}
        <mesh visible={false}
          material={materials.Material__21124}
          geometry={nodes.GlassKC3BG13001.geometry}
          position={[1.5239, 0.7964, 0.5079]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh visible={true}
          material={materials.Glass18reflection}
          geometry={nodes.GlassKC4BG06001.geometry}
          position={[1.1963, 1.0946, 1.8857]}
          rotation={[1.5708, 0, 0]}
          scale={[0.0012, 0.0013, 0.0014]}
        />*/}
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassKC7BG10001.geometry}
          position={[1.4273, 0.7056, -0.068]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0015, 0.0017, 0.0015]}
        />
        <mesh
          material={materials.Glass80eflection}
          geometry={nodes.GlassKC9BG19001.geometry}
          position={[-0.7074, 3.9487, 1.0911]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.0013, -0.0015, -0.0014]}
        />
        {/*
        <group visible={false} position={[0.6449, 0.8179, 1.2363]} rotation={[Math.PI, 1.5705, 0]} scale={[-0.0015, -0.0015, -0.0015]}>
          <mesh material={materials.brick} geometry={nodes.ID4359.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4359_1.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4359_2.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4359_3.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4359_4.geometry} />
        </group>
        <group visible={false} position={[1.1923, 1.4819, 1.4708]} scale={[0.0012, 0.0014, 0.0013]}>
          <mesh material={materials.brick} geometry={nodes.ID3693.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID3693_1.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID3693_2.geometry} />
          <mesh material={materials.white} geometry={nodes.ID3693_3.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID3693_4.geometry} />
        </group>*/}
        <group position={[0.7101, 0.35, 0.5259]} rotation={[0, 1.5705, 0]} scale={[0.0015, 0.0015, 0.0017]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4386.geometry} />
          <mesh material={materials.ggrey} geometry={nodes.ID4386_1.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4386_2.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4386_3.geometry} />
        </group>
        <group position={[-1.0338, 1.2742, 0.7945]} rotation={[0, -1.5705, 0]} scale={[0.0013, 0.0014, 0.0015]}>
          <mesh material={materials.brick} geometry={nodes.ID4431.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4431_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4431_2.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4431_3.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4431_4.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4431_5.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4431_6.geometry} />
        </group>
        <mesh
          material={materials['_20_-_Default.009']}
          geometry={nodes.KC9BG19Blinds001.geometry}
          position={[-0.7115, 0.9238, 0.935]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-0.0013, -0.0015, -0.0014]}
        />
        <group position={[-1.0338, 1.2742, 0.7953]} rotation={[0, -1.5705, 0]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4467.geometry} />
          <mesh material={materials.red} geometry={nodes.ID4467_1.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4467_2.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4467_3.geometry} />
        </group>
      </mesh>
      <mesh material={materials['default']} geometry={nodes.Plane.geometry} position={[-1.86, 0, 2.42]}>
        <mesh
          material={materials['_13_-_Default.043']}
          geometry={nodes.B_court_fence.geometry}
          position={[0.625, 0.4479, -0.5098]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <group position={[0.625, 0.4479, -0.5098]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials['_20_-_Default.008']} geometry={nodes.ID4404.geometry} />
          <mesh material={materials['_08_-_Default.075']} geometry={nodes.ID4404_1.geometry} />
        </group>
        <group position={[0.625, 0.4479, -0.5098]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials.black} geometry={nodes.ID4413.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4413_1.geometry} />
          <mesh material={materials['_02_-_Default.129']} geometry={nodes.ID4413_2.geometry} />
        </group>
        <group position={[1.2956, 1.0182, -1.7525]} scale={[0.0015, 0.0015, 0.0015]}>
          <mesh material={materials.brick} geometry={nodes.ID4197.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4197_1.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4197_2.geometry} />
        </group>
        <group position={[6.7037, 0.4437, -0.125]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0015, 0.0015, 0.0015]}>
          <mesh material={materials['_01_-_Default.096']} geometry={nodes.ID4125.geometry} />
          <mesh material={materials['_03_-_Default.048']} geometry={nodes.ID4125_1.geometry} />
          <mesh material={materials['_08_-_Default.034']} geometry={nodes.ID4125_2.geometry} />
          <mesh material={materials['_01_-_Default.099']} geometry={nodes.ID4125_3.geometry} />
          <mesh material={materials['_03_-_Default.051']} geometry={nodes.ID4125_4.geometry} />
          <mesh material={materials['_02_-_Default.067']} geometry={nodes.ID4125_5.geometry} />
          <mesh material={materials['_07_-_Default.038']} geometry={nodes.ID4125_6.geometry} />
          <mesh material={materials.green} geometry={nodes.ID4125_7.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4125_8.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4125_9.geometry} />
          <mesh material={materials.Material__2487} geometry={nodes.ID4125_10.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4125_11.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4125_12.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4125_13.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4125_14.geometry} />
          <mesh material={materials['_14_-_Default.031']} geometry={nodes.ID4125_15.geometry} />
          <mesh material={materials['_15_-_Default.022']} geometry={nodes.ID4125_16.geometry} />
          <mesh material={materials['_02_-_Default.068']} geometry={nodes.ID4125_17.geometry} />
          <mesh material={materials['_07_-_Default.037']} geometry={nodes.ID4125_18.geometry} />
          <mesh material={materials['_02_-_Default.069']} geometry={nodes.ID4125_19.geometry} />
          <mesh material={materials['_03_-_Default.047']} geometry={nodes.ID4125_20.geometry} />
          <mesh material={materials['_01_-_Default.100']} geometry={nodes.ID4125_21.geometry} />
          <mesh material={materials['_08_-_Default.035']} geometry={nodes.ID4125_22.geometry} />
          <mesh material={materials['_08_-_Default.037']} geometry={nodes.ID4125_23.geometry} />
          <mesh material={materials['_21_-_Default']} geometry={nodes.ID4125_24.geometry} />
          <mesh material={materials['_08_-_Default.039']} geometry={nodes.ID4125_25.geometry} />
          <mesh material={materials['_02_-_Default.070']} geometry={nodes.ID4125_26.geometry} />
          <mesh material={materials['_02_-_Default.071']} geometry={nodes.ID4125_27.geometry} />
          <mesh material={materials['_08_-_Default.038']} geometry={nodes.ID4125_28.geometry} />
        </group>
        <group visible={props.church} position={[-2.4123, 0.4437, -0.8906]} rotation={[-Math.PI, 0, 0]} scale={[-0.0015, -0.0015, -0.0015]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4260.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4260_1.geometry} />
          <mesh material={materials.fire} geometry={nodes.ID4260_2.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4260_3.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4260_4.geometry} />
          <mesh material={materials.orange} geometry={nodes.ID4260_5.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4260_6.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4260_7.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4260_8.geometry} />
        </group>
        <group position={[4.3984, 0.4198, 8.5905]} scale={[0.0536, 0.0666, 0.0536]}>
          <mesh material={materials['bark 3']} geometry={nodes.ID4269.geometry} />
          <mesh material={materials.Foliage} geometry={nodes.ID4269_1.geometry} />
          <mesh material={materials.bark} geometry={nodes.ID4269_2.geometry} />
          <mesh material={materials.Soil} geometry={nodes.ID4269_3.geometry} />
        </group>
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassBG27C1.geometry}
          position={[0.8956, 1.023, -2.2342]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials.Glass35reflection} visible={false}
          geometry={nodes.GlassKC2BG20.geometry}
          position={[2.116, 1.0973, -1.9033]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0016, 0.0016, 0.0015]}
        />
        <mesh 
          material={materials.Material__21124}
          geometry={nodes.GlassKC5BG21.geometry}
          position={[-2.1214, 2.4863, -1.8518]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0023, 0.0017, 0.0016]}
        />
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassKC6BG16.geometry}
          position={[0.4843, 2.951, 1.6028]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <mesh
          material={materials.Glass35reflection} visible={false}
          geometry={nodes.GlassKC7BG17.geometry}
          position={[-1.2998, 0.6586, 1.4628]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials.Glass35reflection} visible={false}
          geometry={nodes.GlassKC8BG06.geometry}
          position={[1.5081, 0.8391, 1.2477]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassKC9BG03.geometry}
          position={[-0.3282, 0.6069, -2.1484]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassKC9BG21.geometry}
          position={[1.8681, 1.0407, -1.436]}
          rotation={[1.5705, 0, Math.PI]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials.Material__21124}
          geometry={nodes.glassSolar_panels.geometry}
          position={[1.6499, 1.6575, -1.8623]}
          rotation={[Math.PI / 2, 1.3156, -Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <group
          position={[1.8048, 0.9748, -1.9382]}
          rotation={[Math.PI, -1.5705, 0]}
          scale={[-0.0016, -0.0015, -0.0016]}>
          <mesh material={materials.ggrey} geometry={nodes.ID4215.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4215_1.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4215_2.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4215_3.geometry} />
        </group>
        <group position={[-1.9046, 0.6581, -2.2849]} scale={[0.0017, 0.0016, 0.0017]}>
          <mesh material={materials['_02_-_Default.097']} geometry={nodes.ID4278.geometry} />
          <mesh material={materials['_02_-_Default.096']} geometry={nodes.ID4278_1.geometry} />
          <mesh material={materials['_08_-_Default.056']} geometry={nodes.ID4278_2.geometry} />
          <mesh material={materials['_15_-_Default.031']} geometry={nodes.ID4278_3.geometry} />
          <mesh material={materials['_19_-_Default.016']} geometry={nodes.ID4278_4.geometry} />
        </group>
        <group position={[0.1174, 0.6313, 2.249]} rotation={[0, -1.5705, 0]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials.white} geometry={nodes.ID4143.geometry} />
          <mesh material={materials.dbrick} geometry={nodes.ID4143_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4143_2.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4143_3.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4143_4.geometry} />
        </group>
        <group position={[1.4961, 0.6236, 1.6351]} rotation={[0, -1.5705, 0]} scale={[0.0015, 0.0015, 0.0015]}>
          <mesh material={materials.dgrey} geometry={nodes.ID4161.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4161_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4161_2.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4161_3.geometry} />
        </group>
        <mesh
          material={materials['_01_-_Default.106']}
          geometry={nodes.KC8BG06_detail.geometry}
          position={[1.4961, 0.6236, 1.6351]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <group position={[0.6626, 0.6069, -1.5654]} rotation={[0, 1.5705, 0]} scale={[0.0015, 0.0015, 0.0015]}>
          <mesh material={materials.white} geometry={nodes.ID4179.geometry} />
          <mesh material={materials.ggrey} geometry={nodes.ID4179_1.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4179_2.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4179_3.geometry} />
        </group>
        <group position={[1.7484, 0.6121, -1.0867]} rotation={[0, 0, -Math.PI]} scale={[-0.0015, -0.0014, -0.0015]}>
          <mesh material={materials.beige} geometry={nodes.ID4242.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4242_1.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4242_2.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4242_3.geometry} />
        </group>
      </mesh>
      <mesh
        material={materials['default']}
        geometry={nodes.Plane003.geometry}
        position={[3.9287, 0, -3.6022]}
        rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          material={materials['_13_-_Default.043']}
          geometry={nodes.B_court_fence001.geometry}
          position={[0.625, 0.4479, -0.5098]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.0014, 0.0014, 0.0014]}
        />
        <group position={[0.625, 0.4479, -0.5098]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials['_20_-_Default.008']} geometry={nodes.ID4404.geometry} />
          <mesh material={materials['_08_-_Default.075']} geometry={nodes.ID4404_1.geometry} />
        </group>
        <group position={[0.625, 0.4479, -0.5098]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0014, 0.0014, 0.0014]}>
          <mesh material={materials.black} geometry={nodes.ID4413.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4413_1.geometry} />
          <mesh material={materials['_02_-_Default.129']} geometry={nodes.ID4413_2.geometry} />
        </group>
        <group position={[1.2956, 1.0182, -1.7525]} scale={[0.0015, 0.0015, 0.0015]}>
          <mesh material={materials.brick} geometry={nodes.ID4197.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4197_1.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4197_2.geometry} />
        </group>
        <group position={[6.4037, 0.4437, -0.125]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.0015, 0.0015, 0.0015]}>
          <mesh material={materials['_01_-_Default.096']} geometry={nodes.ID4125.geometry} />
          <mesh material={materials['_03_-_Default.048']} geometry={nodes.ID4125_1.geometry} />
          <mesh material={materials['_08_-_Default.034']} geometry={nodes.ID4125_2.geometry} />
          <mesh material={materials['_01_-_Default.099']} geometry={nodes.ID4125_3.geometry} />
          <mesh material={materials['_03_-_Default.051']} geometry={nodes.ID4125_4.geometry} />
          <mesh material={materials['_02_-_Default.067']} geometry={nodes.ID4125_5.geometry} />
          <mesh material={materials['_07_-_Default.038']} geometry={nodes.ID4125_6.geometry} />
          <mesh material={materials.green} geometry={nodes.ID4125_7.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4125_8.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4125_9.geometry} />
          <mesh material={materials.Material__2487} geometry={nodes.ID4125_10.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4125_11.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4125_12.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4125_13.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4125_14.geometry} />
          <mesh material={materials['_14_-_Default.031']} geometry={nodes.ID4125_15.geometry} />
          <mesh material={materials['_15_-_Default.022']} geometry={nodes.ID4125_16.geometry} />
          <mesh material={materials['_02_-_Default.068']} geometry={nodes.ID4125_17.geometry} />
          <mesh material={materials['_07_-_Default.037']} geometry={nodes.ID4125_18.geometry} />
          <mesh material={materials['_02_-_Default.069']} geometry={nodes.ID4125_19.geometry} />
          <mesh material={materials['_03_-_Default.047']} geometry={nodes.ID4125_20.geometry} />
          <mesh material={materials['_01_-_Default.100']} geometry={nodes.ID4125_21.geometry} />
          <mesh material={materials['_08_-_Default.035']} geometry={nodes.ID4125_22.geometry} />
          <mesh material={materials['_08_-_Default.037']} geometry={nodes.ID4125_23.geometry} />
          <mesh material={materials['_21_-_Default']} geometry={nodes.ID4125_24.geometry} />
          <mesh material={materials['_08_-_Default.039']} geometry={nodes.ID4125_25.geometry} />
          <mesh material={materials['_02_-_Default.070']} geometry={nodes.ID4125_26.geometry} />
          <mesh material={materials['_02_-_Default.071']} geometry={nodes.ID4125_27.geometry} />
          <mesh material={materials['_08_-_Default.038']} geometry={nodes.ID4125_28.geometry} />
        </group>
        <group visible={props.church2} position={[-2.4123, 0.4437, -0.8906]} rotation={[-Math.PI, 0, 0]} scale={[-0.0015, -0.0015, -0.0015]}>
          <mesh material={materials.lgrey} geometry={nodes.ID4260.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4260_1.geometry} />
          <mesh material={materials.fire} geometry={nodes.ID4260_2.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4260_3.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4260_4.geometry} />
          <mesh material={materials.orange} geometry={nodes.ID4260_5.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4260_6.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4260_7.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4260_8.geometry} />
        </group>
      
        <group visible={props.church3} position={[3.2, 0.4437, -2.7]} rotation={[-Math.PI, 0, 0]} scale={[-0.0015, -0.0015, -0.0015]}>
         
          <mesh material={materials.lgrey} geometry={nodes.ID4260_3.geometry} />
          <mesh material={materials.beige} geometry={nodes.ID4260_4.geometry} />
          <mesh material={materials.orange} geometry={nodes.ID4260_5.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4260_6.geometry} />
          <mesh material={materials.llgrey} geometry={nodes.ID4260_7.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4260_8.geometry} />
        </group>
        <group position={[4.3984, 0.4198, 8.5905]} scale={[0.0536, 0.0666, 0.0536]}>
          <mesh material={materials['bark 3']} geometry={nodes.ID4269.geometry} />
          <mesh material={materials.Foliage} geometry={nodes.ID4269_1.geometry} />
          <mesh material={materials.bark} geometry={nodes.ID4269_2.geometry} />
          <mesh material={materials.Soil} geometry={nodes.ID4269_3.geometry} />
        </group>
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassBG27C1001.geometry}
          position={[0.8956, 1.023, -2.2342]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials.Glass35reflection} visible={false}
          geometry={nodes.GlassKC2BG20001.geometry}
          position={[2.116, 1.0973, -1.9033]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0016, 0.0016, 0.0015]}
        />
        {/*
        <mesh visible={false}
          material={materials.Material__21124}
          geometry={nodes.GlassKC5BG21001.geometry}
          position={[-2.1214, 2.4863, -1.8518]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.0023, 0.0017, 0.0016]}
        />*/}
        <mesh
          material={materials.Glass35reflection} visible={false}
          geometry={nodes.GlassKC7BG17001.geometry}
          position={[-1.2998, 0.6586, 1.4628]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials.Glass35reflection} visible={false}
          geometry={nodes.GlassKC8BG06001.geometry}
          position={[1.5081, 0.8391, 1.2476]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-0.0015, -0.0015, -0.0015]}
        />
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassKC9BG03001.geometry}
          position={[-0.3282, 0.6069, -2.1484]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials.Material__21124}
          geometry={nodes.GlassKC9BG21001.geometry}
          position={[1.8681, 1.0407, -1.436]}
          rotation={[1.5705, 0, Math.PI]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <mesh
          material={materials.Material__21124}
          geometry={nodes.glassSolar_panels001.geometry}
          position={[1.6499, 1.6575, -1.8623]}
          rotation={[Math.PI / 2, 1.3156, -Math.PI / 2]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <group
          position={[1.8048, 0.9748, -1.9382]}
          rotation={[Math.PI, -1.5705, 0]}
          scale={[-0.0016, -0.0015, -0.0016]}>
          <mesh material={materials.ggrey} geometry={nodes.ID4215.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4215_1.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4215_2.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4215_3.geometry} />
        </group>
        {/*}
        <group visible={false} position={[-1.9046, 0.6581, -2.2849]} scale={[0.0017, 0.0016, 0.0017]}>
          <mesh material={materials['_02_-_Default.097']} geometry={nodes.ID4278.geometry} />
          <mesh material={materials['_02_-_Default.096']} geometry={nodes.ID4278_1.geometry} />
          <mesh material={materials['_08_-_Default.056']} geometry={nodes.ID4278_2.geometry} />
          <mesh material={materials['_15_-_Default.031']} geometry={nodes.ID4278_3.geometry} />
          <mesh material={materials['_19_-_Default.016']} geometry={nodes.ID4278_4.geometry} />
      </group>*/}
        <group position={[1.4961, 0.6236, 1.6351]} rotation={[0, -1.5705, 0]} scale={[0.0015, 0.0015, 0.0015]}>
          <mesh material={materials.dgrey} geometry={nodes.ID4161.geometry} />
          <mesh material={materials.white} geometry={nodes.ID4161_1.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4161_2.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4161_3.geometry} />
        </group>
        <mesh
          material={materials['_01_-_Default.106']}
          geometry={nodes.KC8BG06_detail001.geometry}
          position={[1.4961, 0.6236, 1.6351]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0015, 0.0015, 0.0015]}
        />
        <group position={[0.6626, 0.6069, -1.5654]} rotation={[0, 1.5705, 0]} scale={[0.0015, 0.0015, 0.0015]}>
          <mesh material={materials.white} geometry={nodes.ID4179.geometry} />
          <mesh material={materials.ggrey} geometry={nodes.ID4179_1.geometry} />
          <mesh material={materials.brick} geometry={nodes.ID4179_2.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4179_3.geometry} />
        </group>
        <group position={[1.7484, 0.6121, -1.0867]} rotation={[0, 0, -Math.PI]} scale={[-0.0015, -0.0014, -0.0015]}>
          <mesh material={materials.beige} geometry={nodes.ID4242.geometry} />
          <mesh material={materials.black} geometry={nodes.ID4242_1.geometry} />
          <mesh material={materials.lgrey} geometry={nodes.ID4242_2.geometry} />
          <mesh material={materials.dgrey} geometry={nodes.ID4242_3.geometry} />
        </group>
      </mesh>
      <mesh visible={props.gas}
        material={materials['default']}
        geometry={nodes.Plane004.geometry}
        position={[-0.26, 0.4, -4.66]}
        rotation={[0, 1.5464, 0]}
        scale={[0.06, 0.06, 0.06]}>
        <mesh
          material={materials['Material #1431659661.001']}
          geometry={nodes['3'].geometry}
          position={[-18.5665, 5.1, -0.6424]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.0087, 0.0087, 0.0087]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box150.geometry}
          position={[4.0201, 5.2458, -12.6835]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box151.geometry}
          position={[4.0201, 5.192, -10.6723]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box152.geometry}
          position={[4.0201, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box153.geometry}
          position={[2.0185, 5.2458, -12.6835]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box154.geometry}
          position={[2.0185, 5.192, -10.6723]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box155.geometry}
          position={[2.0185, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box156.geometry}
          position={[-0.0108, 5.2458, -12.6835]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box157.geometry}
          position={[-0.0108, 5.192, -10.6723]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box158.geometry}
          position={[-0.0108, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box159.geometry}
          position={[-2.011, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Light}
          geometry={nodes.Box160.geometry}
          position={[-4.0105, 5.1389, -8.684]}
          rotation={[0.0267, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.signs}
          geometry={nodes.carwash.geometry}
          position={[11.7435, 5.0715, -10.3245]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.signs}
          geometry={nodes.carwash_icon.geometry}
          position={[11.7435, 6.4715, -7.4337]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <group visible={true} position={[-6.4368, 5.74, -1.5349]} rotation={[0, -1.5705, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659657']} geometry={nodes.Mesh001.geometry} />
          <mesh material={materials['Main color']} geometry={nodes.Mesh001_1.geometry} />
          <mesh material={materials['Material #1431659645']} geometry={nodes.Mesh001_2.geometry} />
        </group>
        <mesh
          material={materials['Material #1431659644']}
          geometry={nodes.Circle002.geometry}
          position={[-7.6159, 1.14, -0.9995]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659644']}
          geometry={nodes.Circle003.geometry}
          position={[-7.6159, 1.14, 4.5298]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659644']}
          geometry={nodes.Circle004.geometry}
          position={[5.2982, 1.14, 4.5297]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659644']}
          geometry={nodes.Circle005.geometry}
          position={[5.2982, 1.14, -0.9996]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.black}
          geometry={nodes.Cube.geometry}
          position={[6.0364, 2.6827, -13.5124]}
          rotation={[-Math.PI / 2, 0, -0.356]}
          scale={[-0.052, -0.4, -0.7332]}
        />
        <group
          position={[6.0846, 2.67, -6.6496]}
          rotation={[-3.1367, -0.5636, 3.1409]}
          scale={[0.4153, 0.7383, 0.0954]}>
          <mesh material={materials.black} geometry={nodes.Cube007_1.geometry} />
          <mesh material={materials.black} geometry={nodes.Cube007_2.geometry} />
        </group>
        <group position={[3.9859, 3.07, 4.7165]} rotation={[0.1434, 0, 0]} scale={[0.3945, 0.223, 0.0448]}>
          <mesh material={materials.plastic} geometry={nodes.Cube008.geometry} />
          <mesh material={materials.screen} geometry={nodes.Cube008_1.geometry} />
        </group>
        <mesh
          material={materials.black}
          geometry={nodes.Cube004.geometry}
          position={[6.3152, 2.6827, -14.2621]}
          rotation={[-Math.PI / 2, 0, -0.356]}
          scale={[-0.052, -0.4, -0.7332]}
        />
        <mesh
          material={materials.black}
          geometry={nodes.Cube005.geometry}
          position={[5.7566, 2.6827, -12.7602]}
          rotation={[-Math.PI / 2, 0, -0.356]}
          scale={[-0.052, -0.4, -0.7332]}
        />
        <mesh
          material={materials['Material.002']}
          geometry={nodes.Cube006.geometry}
          position={[-1.5675, 2.808, -10.772]}
          scale={[7.08, 1.7, 3.02]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Cube007.geometry}
          position={[3.9859, 3.07, 4.3565]}
          rotation={[0.7696, 0.3074, 1.681]}
          scale={[0.353, 0.4368, 0.0448]}
        />
        <group position={[5.2883, 1.1019, -9.1454]} rotation={[0, -1.5705, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Chrome_Slightly_Worn.001']} geometry={nodes.Mesh171.geometry} />
          <mesh material={materials['plastic black']} geometry={nodes.Mesh171_1.geometry} />
        </group>
        <mesh
          material={materials['Main color']}
          geometry={nodes.gaspump002.geometry}
          position={[3.977, 1.14, 4.5297]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Main color']}
          geometry={nodes.gaspump003.geometry}
          position={[3.977, 1.14, -0.9996]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Main color']}
          geometry={nodes.Line001.geometry}
          position={[-1.5897, 5.2344, -10.6107]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Main color']}
          geometry={nodes.Line002.geometry}
          position={[14.8841, 5.2344, -2.3011]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.Material__2121708538}
          geometry={nodes.Object058.geometry}
          position={[-4.8229, 3.0202, -7.767]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0082, 0.0082, 0.0082]}
        />
        <group position={[-1.5676, 0.9585, -1.2862]} rotation={[Math.PI, 0, Math.PI]} scale={[0.0121, 0.0121, 0.0121]}>
          <mesh material={materials['Material #26']} geometry={nodes.Mesh011.geometry} />
          <mesh material={materials['Material #180']} geometry={nodes.Mesh011_1.geometry} />
        </group>
        <mesh
          material={materials['default']}
          geometry={nodes.Object067.geometry}
          position={[10.5751, 0.9205, 16.3191]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.0121, 0.0121, 0.0121]}
        />
        <mesh
          material={materials['default']}
          geometry={nodes.Object068.geometry}
          position={[14.0191, 1.08, -4.2776]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659658']}
          geometry={nodes.Object070.geometry}
          position={[14.0191, 1.08, -18.8464]}
          rotation={[Math.PI, 0, 0]}
          scale={[-0.01, -0.01, -0.01]}
        />
        <mesh
          material={materials['Material #1431659659']}
          geometry={nodes.Object071.geometry}
          position={[-6.4368, 5.74, -1.5349]}
          rotation={[0, -1.5705, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659659']}
          geometry={nodes.Object072.geometry}
          position={[21.0266, 4.3587, -6.3414]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659659']}
          geometry={nodes.Object073.geometry}
          position={[-6.895, 5.7187, -16.7606]}
          rotation={[0.1536, -Math.PI / 2, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials.black}
          geometry={nodes.order_menu.geometry}
          position={[5.9, 1.58, -13.58]}
          rotation={[Math.PI / 2, 0, 0.356]}
          scale={[0.02, 0.01, 0.02]}
        />
        <mesh
          material={materials.plastic}
          geometry={nodes.portrait_promotional_stand.geometry}
          position={[5.94, 1.58, -6.8]}
          rotation={[Math.PI / 2, 0, 1.0018]}
          scale={[0.02, 0.01, 0.02]}
        />
        <group position={[-18.1297, 5.28, -11.5342]} rotation={[0, -1.5705, 0]} scale={[-0.01, -0.01, -0.01]}>
          <mesh material={materials['Material #1431659674']} geometry={nodes.Mesh002.geometry} />
          <mesh material={materials['Material #1431659673']} geometry={nodes.Mesh002_1.geometry} />
        </group>
        <group position={[-6.2834, 1.04, -0.9995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659630']} geometry={nodes.Mesh003.geometry} />
          <mesh material={materials['Material #1431659226']} geometry={nodes.Mesh003_1.geometry} />
        </group>
        <group
          position={[11.2666, 1.28, -7.3554]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-0.01, -0.01, -0.01]}>
          <mesh material={materials.white} geometry={nodes.Mesh007.geometry} />
          <mesh material={materials.Glass} geometry={nodes.Mesh007_1.geometry} />
        </group>
        <group position={[-6.9721, 5.7349, -2.7578]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh012.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh012_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh012_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh012_3.geometry} />
          <mesh material={materials['Material #1431659088']} geometry={nodes.Mesh012_4.geometry} />
        </group>
        <mesh
          material={materials['Material #1431659657']}
          geometry={nodes.Rectangle135.geometry}
          position={[-6.6557, 4.68, -7.5]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659626']}
          geometry={nodes.Rectangle137.geometry}
          position={[-1.5962, 1.08, -10.4045]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659657']}
          geometry={nodes.Rectangle140.geometry}
          position={[14.3412, 4.68, -9.4243]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <group position={[-1.1368, 5.7349, -2.7578]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh029.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh029_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh029_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh029_3.geometry} />
          <mesh material={materials['Material #1431659088']} geometry={nodes.Mesh029_4.geometry} />
        </group>
        <group position={[4.6985, 5.7349, -2.7578]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh030.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh030_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh030_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh030_3.geometry} />
          <mesh material={materials['Material #1431659088']} geometry={nodes.Mesh030_4.geometry} />
        </group>
        <group position={[-6.9721, 5.7349, 1.7651]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh031.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh031_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh031_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh031_3.geometry} />
          <mesh material={materials['Material #1431659088']} geometry={nodes.Mesh031_4.geometry} />
        </group>
        <group position={[-1.1368, 5.7349, 1.7651]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh032.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh032_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh032_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh032_3.geometry} />
        </group>
        <group position={[4.6985, 5.7349, 1.7651]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh033.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh033_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh033_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh033_3.geometry} />
          <mesh material={materials['Material #1431659088']} geometry={nodes.Mesh033_4.geometry} />
        </group>
        <group position={[-6.9721, 5.7349, 6.288]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh034.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh034_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh034_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh034_3.geometry} />
        </group>
        <group position={[-1.1368, 5.7349, 6.288]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh035.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh035_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh035_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh035_3.geometry} />
          <mesh material={materials['Material #1431659088']} geometry={nodes.Mesh035_4.geometry} />
        </group>
        <group position={[4.6985, 5.7349, 6.288]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659086']} geometry={nodes.Mesh036.geometry} />
          <mesh material={materials['01 - Defaultsaed']} geometry={nodes.Mesh036_1.geometry} />
          <mesh material={materials.steklo} geometry={nodes.Mesh036_2.geometry} />
          <mesh material={materials['Material #1431659087']} geometry={nodes.Mesh036_3.geometry} />
          <mesh material={materials['Material #1431659088']} geometry={nodes.Mesh036_4.geometry} />
        </group>
        <mesh
          material={materials['Material #1431659626']}
          geometry={nodes.Rectangle153.geometry}
          position={[-1.1368, 1.08, 1.7651]}
          scale={[0.01, 0.01, 0.01]}
        />
        <group position={[-6.2834, 1.04, 4.5298]} rotation={[Math.PI, 0, Math.PI]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659630']} geometry={nodes.Mesh043.geometry} />
          <mesh material={materials['Material #1431659226']} geometry={nodes.Mesh043_1.geometry} />
        </group>
        <mesh
          material={materials['Main color']}
          geometry={nodes.Rectangle157.geometry}
          position={[1.356, 1.54, 4.5297]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Main color']}
          geometry={nodes.Rectangle158.geometry}
          position={[2.4375, 1.1386, 4.5297]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <group position={[3.9657, 1.04, 4.5297]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659630']} geometry={nodes.Mesh048.geometry} />
          <mesh material={materials['Material #1431659226']} geometry={nodes.Mesh048_1.geometry} />
        </group>
        <mesh
          material={materials['Main color']}
          geometry={nodes.Rectangle160.geometry}
          position={[1.356, 1.54, -0.9996]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Main color']}
          geometry={nodes.Rectangle161.geometry}
          position={[2.6775, 1.1386, -0.9996]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.01, 0.01, 0.01]}
        />
        <group position={[3.9657, 1.04, -0.9996]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659630']} geometry={nodes.Mesh053.geometry} />
          <mesh material={materials['Material #1431659226']} geometry={nodes.Mesh053_1.geometry} />
        </group>
        <mesh
          material={materials['Material #1431659627']}
          geometry={nodes.Shape001.geometry}
          position={[-1.5962, 1.08, -10.4045]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          material={materials['Material #1431659627']}
          geometry={nodes.Shape002.geometry}
          position={[-1.1368, 1.08, 1.7651]}
          scale={[0.01, 0.01, 0.01]}
        />
        <group position={[-7.7988, 4.4933, 7.7627]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials['Material #1431659660']} geometry={nodes.Mesh061.geometry} />
          <mesh material={materials['Main color']} geometry={nodes.Mesh061_1.geometry} />
        </group>
        <mesh
          material={materials.black}
          geometry={nodes.speaker_box.geometry}
          position={[6.1933, 1.5157, -13.4745]}
          rotation={[Math.PI / 2, 0, 0.356]}
          scale={[0.0724, 0.0938, 0.4688]}
        />
        <mesh
          material={materials.plastic}
          geometry={nodes.Top_stand.geometry}
          position={[4.0059, 2.83, 4.5365]}
          scale={[0.38, 0.1, 0.14]}
        />
        <mesh
          material={materials['Material #9']}
          geometry={nodes.vorota002.geometry}
          position={[25.0899, 1.0459, 37.2974]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0093, 0.0094, 0.0093]}
        />
        <mesh
          material={materials['Material #9']}
          geometry={nodes.vorota003.geometry}
          position={[25.0899, 1.0459, 42.8973]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0093, 0.0094, 0.0093]}
        />
        <mesh
          material={materials['Material #9']}
          geometry={nodes.vorota01.geometry}
          position={[25.0899, 1.0459, 31.6974]}
          rotation={[0, -1.5705, 0]}
          scale={[0.0093, 0.0094, 0.0093]}
        />
      </mesh>
      <mesh
        material={materials['Glass18reflection.001']}
        geometry={nodes.GlassKC4BG06002.geometry}
        position={[3.2072, 1.1719, -5.2661]}
        rotation={[Math.PI / 2, 0, 1.6054]}
        scale={[0.0008, 0.0013, 0.0014]}
      />
      <group
        position={[3.622, 1.5592, -5.2557]}
        rotation={[Math.PI, -1.5362, Math.PI]}
        scale={[0.0008, 0.0014, 0.0013]}>
        <mesh material={materials.brick} geometry={nodes.ID3693001.geometry} />
        <mesh material={materials.white} geometry={nodes.ID3693001_1.geometry} />
        <mesh material={materials.ggrey} geometry={nodes.ID3693001_2.geometry} />
        <mesh material={materials.black} geometry={nodes.ID3693001_3.geometry} />
        <mesh material={materials.lgrey} geometry={nodes.ID3693001_4.geometry} />
      </group>
    </group>
  </>)
}

useGLTF.preload(dscf)
