/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import cstore from './ncstore2.glb'
import icon from './icons.png'


export default function Store(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(cstore)

  materials['Glass.004'].transparent = true;
  materials['signs.002'].transparent = true;
  materials['signs.002'].alphaMap = useTexture(icon);


  
 
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1.6, 0.02, -10.4]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow
          material={materials['Material #1431659626.003']}
          geometry={nodes.Rectangle137.geometry}
          position={[0, 2.42, 0]}
        />
        <mesh castShadow receiveShadow
          material={materials['Material #1431659627.003']}
          geometry={nodes.Shape001.geometry}
          position={[0, 2.42, 0]}
        />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Chrome_Slightly_Worn.003']}
        geometry={nodes.Box047.geometry}
        position={[4.32, 0.71, -9.15]}
        rotation={[0, -1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Chrome_Slightly_Worn.003']}
        geometry={nodes.Box048.geometry}
        position={[3.63, 0.71, -9.15]}
        rotation={[0, -1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Plastic_Shiny.003']}
        geometry={nodes.Box053.geometry}
        position={[3.38, 0.16, -11.96]}
        rotation={[Math.PI, 1.57, 0]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Plastic_Shiny.003']}
        geometry={nodes.Box054.geometry}
        position={[4.08, 0.22, -11.16]}
        rotation={[Math.PI, 1.57, 0]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <group position={[3.83, 0.54, -11.18]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh430.geometry} />
        <mesh castShadow receiveShadow material={materials['Plastic_Shiny.003']} geometry={nodes.Mesh430_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Plastic_Shiny.003']}
        geometry={nodes.Box056.geometry}
        position={[4.08, 0.56, -11.16]}
        rotation={[Math.PI, 1.57, 0]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <group position={[-0.4, 0.08, -13.46]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['soda.003']} geometry={nodes.Mesh428.geometry} />
        <mesh castShadow receiveShadow material={materials['fridge int.002']} geometry={nodes.Mesh428_1.geometry} />
        <mesh castShadow receiveShadow material={materials['Car_Paint_Metallic.003']} geometry={nodes.Mesh428_2.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box150.geometry}
        position={[4.02, 4.21, -12.68]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box151.geometry}
        position={[4.02, 4.15, -10.67]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box152.geometry}
        position={[4.02, 4.1, -8.68]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box153.geometry}
        position={[2.02, 4.21, -12.68]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box154.geometry}
        position={[2.02, 4.15, -10.67]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box155.geometry}
        position={[2.02, 4.1, -8.68]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box156.geometry}
        position={[-0.01, 4.21, -12.68]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box157.geometry}
        position={[-0.01, 4.15, -10.67]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box158.geometry}
        position={[-0.01, 4.1, -8.68]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box159.geometry}
        position={[-2.01, 4.1, -8.68]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Light.002']}
        geometry={nodes.Box160.geometry}
        position={[-4.01, 4.1, -8.68]}
        rotation={[0.03, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Stainless_Steel.003']}
        geometry={nodes.Box162.geometry}
        position={[-3.05, 1.34, -13.75]}
        rotation={[0, -1.57, 0]}
        scale={[0.01, 0.01, 0.02]}
      />
      <mesh castShadow receiveShadow
        material={materials['Stainless_Steel.003']}
        geometry={nodes.Box163.geometry}
        position={[-5.92, 1.34, -13.75]}
        rotation={[0, -1.57, 0]}
        scale={[0.01, 0.01, 0.02]}
      />
      <group position={[3.05, 0.14, -11.02]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['orange.002']} geometry={nodes.Mesh414.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh414_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['default']}
        geometry={nodes.Cube006.geometry}
        position={[-8.46, 2.11, -10.84]}
        scale={[0.27, 2.12, 3.1]}
      />
      <mesh castShadow receiveShadow
        material={materials['default']}
        geometry={nodes.Cube008.geometry}
        position={[-1.48, 2.05, -13.78]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.01, 2.2, 6.88]}
      />
      <group position={[3.01, 1.22, -12.08]} rotation={[0, 0, -Math.PI / 6]} scale={[0.02, 0.18, 0.1]}>
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Cube059.geometry} />
        <mesh castShadow receiveShadow material={materials['screen.005']} geometry={nodes.Cube059_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['plastic black.005']}
        geometry={nodes.Cube011.geometry}
        position={[3.05, 0.96, -12.12]}
        rotation={[Math.PI, 0, 0]}
        scale={[-0.04, -0.02, -0.08]}
      />
      <mesh castShadow receiveShadow
        material={materials['default']}
        geometry={nodes.Cube012.geometry}
        position={[4.76, 1.75, -7.82]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.22, 1.74, 0.49]}
      />
      <mesh castShadow receiveShadow
        material={materials['default']}
        geometry={nodes.Cube013.geometry}
        position={[-6.42, 1.72, -7.71]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.1, 1.72, 2.3]}
      />
      <group position={[2.12, 2.08, -13.64]} rotation={[0.09, 1.57, 0]} scale={[0.07, 0.63, 1.12]}>
        <mesh castShadow receiveShadow material={materials['plastic black.004']} geometry={nodes.Cube055.geometry} />
        <mesh castShadow receiveShadow material={materials['screen.004']} geometry={nodes.Cube055_1.geometry} />
      </group>
      <group position={[5.04, 2.08, -10.29]} scale={[0.07, 0.63, 1.12]}>
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Cube054.geometry} />
        <mesh castShadow receiveShadow material={materials['screen.005']} geometry={nodes.Cube054_1.geometry} />
      </group>
      <group position={[-5.91, 0.9, -10.73]} rotation={[Math.PI, 0, 2.57]} scale={[0.02, 0.21, 0.12]}>
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Cube053.geometry} />
        <mesh castShadow receiveShadow material={materials['screen.005']} geometry={nodes.Cube053_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['orange.002']}
        geometry={nodes.Cube017.geometry}
        position={[-5.93, 0.45, -10.73]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.1, 0.4, 0.08]}
      />
      <group position={[-7.26, 2.4, -11.83]} scale={[0.04, 0.36, 0.64]}>
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Cube051.geometry} />
        <mesh castShadow receiveShadow material={materials['screen.005']} geometry={nodes.Cube051_1.geometry} />
      </group>
      <group position={[-7.26, 2.4, -10.57]} scale={[0.04, 0.36, 0.64]}>
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Cube050.geometry} />
        <mesh castShadow receiveShadow material={materials['screen.005']} geometry={nodes.Cube050_1.geometry} />
      </group>
      <group position={[-7.26, 2.4, -9.31]} scale={[0.04, 0.36, 0.64]}>
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Cube049.geometry} />
        <mesh castShadow receiveShadow material={materials['screen.005']} geometry={nodes.Cube049_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['default']}
        geometry={nodes.Cube021.geometry}
        position={[5.29, 1.75, -10.68]}
        scale={[0.09, 1.74, 3.09]}
      />
      <mesh castShadow receiveShadow
        material={materials['default']}
        geometry={nodes.Cube022.geometry}
        position={[-1.2, 3.25, -7.71]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.11, 5.63, 0.22]}
      />
      <mesh castShadow receiveShadow
        material={materials['plastic black.005']}
        geometry={nodes.Cylinder.geometry}
        position={[3.05, 1.12, -12.12]}
        scale={[0.02, 0.16, 0.02]}
      />
      <group position={[2.04, 0.06, -9.15]} rotation={[0, -1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh413.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh413_1.geometry} />
      </group>
      <group position={[2.65, 0.06, -9.15]} rotation={[0, -1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh412.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh412_1.geometry} />
      </group>
      <group position={[2.67, 0.57, -9.15]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh411.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh411_1.geometry} />
      </group>
      <group position={[3.31, 0.06, -9.15]} rotation={[0, -1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh410.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh410_1.geometry} />
      </group>
      <group position={[4.62, 0.06, -9.15]} rotation={[0, -1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh409.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh409_1.geometry} />
      </group>
      <group position={[4.64, 0.57, -9.15]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh408.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh408_1.geometry} />
      </group>
      <group position={[5.29, 0.06, -9.15]} rotation={[0, -1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh407.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh407_1.geometry} />
      </group>
      <group position={[2.03, 0.57, -9.15]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh406.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh406_1.geometry} />
      </group>
      <group position={[1.38, 0.06, -9.15]} rotation={[Math.PI, -1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh405.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh405_1.geometry} />
      </group>
      <group position={[-0.39, 0.33, -13.19]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Glass.005']} geometry={nodes.Mesh404.geometry} />
        <mesh castShadow receiveShadow material={materials['Stainless_Steel.003']} geometry={nodes.Mesh404_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Material #1431659628.003']}
        geometry={nodes.Line001.geometry}
        position={[-1.59, 4.19, -10.61]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group position={[-7, 0.63, -11.15]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Plastic_Shiny.003']} geometry={nodes.Mesh402.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh402_1.geometry} />
        <mesh castShadow receiveShadow material={materials['Stainless_Steel.003']} geometry={nodes.Mesh402_2.geometry} />
        <mesh castShadow receiveShadow material={materials['orange.002']} geometry={nodes.Mesh402_3.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['signs.002']}
        geometry={nodes.market.geometry}
        position={[0.23, 19.53, -7.47]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['signs.002']}
        geometry={nodes.market_icon.geometry}
        position={[-19.88, 4.64, -7.47]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['plastic black.005']}
        geometry={nodes.Object027.geometry}
        position={[3.38, 0.16, -11.96]}
        rotation={[Math.PI, 1.57, 0]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <group position={[3.38, 0.16, -11.96]} rotation={[Math.PI, 1.57, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh398.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh398_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Rubber_clean.003']}
        geometry={nodes.Object029001.geometry}
        position={[3.24, 1.16, -11.68]}
        rotation={[Math.PI / 2, -1.13, -Math.PI / 2]}
        scale={[-0.01, -0.01, -0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Material #2121708537.002']}
        geometry={nodes.Object057001.geometry}
        position={[-3.05, 1.34, -13.75]}
        rotation={[0, -1.57, 0]}
        scale={[0.01, 0.01, 0.02]}
      />
      <mesh castShadow receiveShadow
        material={materials['Material #2121708538.002']}
        geometry={nodes.Object058001.geometry}
        position={[-5.92, 1.34, -13.75]}
        rotation={[0, -1.57, 0]}
        scale={[0.01, 0.01, 0.02]}
      />
      <mesh castShadow receiveShadow
        material={materials['Material #1431659659.003']}
        geometry={nodes.Object073.geometry}
        position={[-6.89, 4.68, -16.76]}
        rotation={[0.15, -Math.PI / 2, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['plastic.007']}
        geometry={nodes.order_menu.geometry}
        position={[5.9, 0.54, -13.58]}
        rotation={[Math.PI / 2, 0, 0.36]}
        scale={[0.02, 0.01, 0.02]}>
        <group position={[7.57, 1.58, -55.14]} rotation={[-Math.PI, 0, 0]} scale={[-2.6, -40, -36.66]}>
          <mesh castShadow receiveShadow material={materials['plastic.007']} geometry={nodes.Cube065.geometry} />
          <mesh castShadow receiveShadow material={materials['Screen.012']} geometry={nodes.Cube065_1.geometry} />
        </group>
        <group position={[7.57, -78.4, -55.14]} rotation={[-Math.PI, 0, 0]} scale={[-2.6, -40, -36.66]}>
          <mesh castShadow receiveShadow material={materials['plastic.006']} geometry={nodes.Cube063.geometry} />
          <mesh castShadow receiveShadow material={materials['Screen.012']} geometry={nodes.Cube063_1.geometry} />
        </group>
        <group position={[7.57, 81.84, -55.14]} rotation={[-Math.PI, 0, 0]} scale={[-2.6, -40, -36.66]}>
          <mesh castShadow receiveShadow material={materials['plastic.005']} geometry={nodes.Cube062.geometry} />
          <mesh castShadow receiveShadow material={materials['Screen.012']} geometry={nodes.Cube062_1.geometry} />
        </group>
        <mesh castShadow receiveShadow
          material={materials['plastic.007']}
          geometry={nodes.speaker_box.geometry}
          position={[15.58, -0.34, 3.21]}
          scale={[3.62, 9.38, 23.44]}>
          <mesh castShadow receiveShadow
            material={materials['Material.007']}
            geometry={nodes.Sphere.geometry}
            position={[0.2, 0, -0.69]}
            scale={[1.06, 0.86, 0.16]}
          />
          <mesh castShadow receiveShadow
            material={materials['default']}
            geometry={nodes.Text.geometry}
            position={[1.06, 0.14, -0.81]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </mesh>
      </mesh>
      <mesh castShadow receiveShadow
        material={materials['Material #178.002']}
        geometry={nodes.Plane003.geometry}
        position={[-0.53, 1.43, -7.53]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['plastic.007']}
        geometry={nodes.portrait_promotional_stand.geometry}
        position={[5.94, 0.54, -6.8]}
        rotation={[Math.PI / 2, 0, 1]}
        scale={[0.02, 0.01, 0.02]}>
        <group position={[10.23, -4.08, -54.5]} rotation={[1.03, -1.57, 2.6]} scale={[41.53, 36.91, 4.77]}>
          <mesh castShadow receiveShadow material={materials['plastic.007']} geometry={nodes.Cube064.geometry} />
          <mesh castShadow receiveShadow material={materials['Screen.012']} geometry={nodes.Cube064_1.geometry} />
        </group>
      </mesh>
      <group position={[2.13, 0.81, -8.87]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh392.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh392_1.geometry} />
      </group>
      <group position={[2.13, 0.81, -9.42]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh391.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh391_1.geometry} />
      </group>
      <group position={[2.67, 0.95, -9.15]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh390.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh390_1.geometry} />
      </group>
      <group position={[2.65, 0.95, -9.16]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh389.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh389_1.geometry} />
      </group>
      <group position={[11.27, 2.91, -7.83]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #2.002']} geometry={nodes.Mesh388.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #3.002']} geometry={nodes.Mesh388_1.geometry} />
        <mesh castShadow receiveShadow materialOpacity={0.5} material={materials['Glass.004']} geometry={nodes.Mesh388_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #59 Slot #5.002']} geometry={nodes.Mesh388_3.geometry} />
      </group>
      <group position={[3.64, 0.8, -9.15]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh387.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh387_1.geometry} />
      </group>
      <group position={[4.3, 0.8, -9.15]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.01, -0.01, -0.01]}>
        <mesh castShadow receiveShadow material={materials['Chrome_Slightly_Worn.003']} geometry={nodes.Mesh386.geometry} />
        <mesh castShadow receiveShadow material={materials['plastic black.005']} geometry={nodes.Mesh386_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Material #1431659657.003']}
        geometry={nodes.Rectangle135.geometry}
        position={[-6.66, 3.64, -7.5]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Material #1189.002']}
        geometry={nodes.screen011001.geometry}
        position={[3.24, 1.16, -11.68]}
        rotation={[Math.PI / 2, -1.13, -Math.PI / 2]}
        scale={[-0.01, -0.01, -0.01]}
      />
    </group>
  )
}

useGLTF.preload('/ncstore2.glb')
