/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import npump from './npump.glb';
import ntiles from './tiles_normal.jpg';
import * as THREE from 'three';
import icon from './icons.png'

export default function Pump(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(npump)
  materials['Material #1431659661.002'].transparent = true;

  materials['Material #1431659661.002'].alphaMap = useTexture(icon);


  materials['Material #1431659628.001'].roughness = 0.4;
  materials['Material #1431659628.001'].metalness = 0.3;

  const ntex = useTexture(ntiles);
  ntex.wrapS = 1;
  ntex.wrapT = 1;
  materials['Material #1431659626.001'].normalMap = ntex;
  materials['Material #1431659626.001'].metalness = 0.4;
  materials['Material #1431659626.001'].roughness = 0.3;
  materials['Material #1431659626.001'].normalScale = new THREE.Vector2(4,4);
  
  
  return (
    <group  ref={group} {...props} dispose={null}>
      <group position={[-1.14, 0.02, 1.77]} scale={[0.01, 0.01, 0.01]}>
        <mesh  castShadow receiveShadow
          material={materials['Material #1431659626.001']}
          geometry={nodes.Rectangle153.geometry}
          position={[0, 2.42, 0]}
        />
        <mesh  castShadow receiveShadow
          material={materials['Material #1431659627.001']}
          geometry={nodes.Shape002.geometry}
          position={[0, 2.42, 0]}
        />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Material #1431659661.002']}
        geometry={nodes['2'].geometry}
        position={[-10.72, 3.9, 4.89]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow
        material={materials['Material #1431659661.002']}
        geometry={nodes['4'].geometry}
        position={[-10.72, 4.3, -0.64]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group position={[-6.44, 4.7, -1.53]} rotation={[0, -1.57, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659657.001']} geometry={nodes.Mesh179.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659628.001']} geometry={nodes.Mesh179_1.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659645.001']} geometry={nodes.Mesh179_2.geometry} />
      </group>
      <mesh  castShadow receiveShadow
        material={materials['Material #1431659644.001']}
        geometry={nodes.Circle002.geometry}
        position={[-7.62, 0.1, -1]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Material #1431659644.001']}
        geometry={nodes.Circle003.geometry}
        position={[-7.62, 0.1, 4.53]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow
        material={materials['Material #1431659644.001']}
        geometry={nodes.Circle004.geometry}
        position={[5.3, 0.1, 4.53]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow
        material={materials['Material #1431659644.001']}
        geometry={nodes.Circle005.geometry}
        position={[5.3, 0.1, -1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow
        material={materials['plastic.001']}
        geometry={nodes.Cube.geometry}
        position={[2.95, 0.96, 4.9]}
        rotation={[0.77, 0, 0]}
        scale={[0.11, 0.01, 0.22]}
      />
      <group position={[3.98, 0.1, 4.53]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Gas Pumps.001']} geometry={nodes.Mesh174.geometry} />
        <mesh castShadow receiveShadow material={materials['Gas Pump Screen.001']} geometry={nodes.Mesh174_1.geometry} />
        <mesh castShadow receiveShadow material={materials['Pump metel trim.001']} geometry={nodes.Mesh174_2.geometry} />
      </group>
      <group position={[3.98, 0.1, -1]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Gas Pumps.001']} geometry={nodes.Mesh147.geometry} />
        <mesh castShadow receiveShadow material={materials['Gas Pump Screen.001']} geometry={nodes.Mesh147_1.geometry} />
        <mesh castShadow receiveShadow material={materials['Pump metel trim.001']} geometry={nodes.Mesh147_2.geometry} />
      </group>
      <mesh  castShadow receiveShadow
        material={materials['Material #1431659659.001']}
        geometry={nodes.Object071.geometry}
        position={[-6.44, 4.7, -1.53]}
        rotation={[0, -1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group position={[-6.97, 4.69, -2.76]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh145.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh145_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh145_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh145_3.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659088.001']} geometry={nodes.Mesh145_4.geometry} />
      </group>
      <group position={[-1.14, 4.69, -2.76]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh144.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh144_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh144_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh144_3.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659088.001']} geometry={nodes.Mesh144_4.geometry} />
      </group>
      <group position={[4.7, 4.69, -2.76]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh143.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh143_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh143_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh143_3.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659088.001']} geometry={nodes.Mesh143_4.geometry} />
      </group>
      <group position={[-6.97, 4.69, 1.77]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh132.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh132_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh132_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh132_3.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659088.001']} geometry={nodes.Mesh132_4.geometry} />
      </group>
      <group position={[-1.14, 4.69, 1.77]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh131.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh131_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh131_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh131_3.geometry} />
      </group>
      <group position={[4.7, 4.69, 1.77]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh130.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh130_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh130_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh130_3.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659088.001']} geometry={nodes.Mesh130_4.geometry} />
      </group>
      <group position={[-6.97, 4.69, 6.29]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh129.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh129_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh129_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh129_3.geometry} />
      </group>
      <group position={[-1.14, 4.69, 6.29]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh128.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh128_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh128_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh128_3.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659088.001']} geometry={nodes.Mesh128_4.geometry} />
      </group>
      <group position={[4.7, 4.69, 6.29]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659086.001']} geometry={nodes.Mesh127.geometry} />
        <mesh castShadow receiveShadow material={materials['01 - Defaultsaed.001']} geometry={nodes.Mesh127_1.geometry} />
        <mesh castShadow receiveShadow material={materials['steklo.001']} geometry={nodes.Mesh127_2.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659087.001']} geometry={nodes.Mesh127_3.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659088.001']} geometry={nodes.Mesh127_4.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Material #1431659630.001']}
        geometry={nodes.Rectangle157.geometry}
        position={[1.36, 0.5, 4.53]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Trash can.001']}
        geometry={nodes.Rectangle158.geometry}
        position={[2.44, 0.1, 4.53]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group position={[3.97, 0, 4.53]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659630.001']} geometry={nodes.Mesh078.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659226.001']} geometry={nodes.Mesh078_1.geometry} />
      </group>
      <mesh castShadow receiveShadow
        material={materials['Material #1431659630.001']}
        geometry={nodes.Rectangle160.geometry}
        position={[1.36, 0.5, -1]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh castShadow receiveShadow
        material={materials['Trash can.001']}
        geometry={nodes.Rectangle161.geometry}
        position={[2.68, 0.1, -1]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group position={[3.97, 0, -1]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659630.001']} geometry={nodes.Mesh075.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659226.001']} geometry={nodes.Mesh075_1.geometry} />
      </group>
      <group position={[-7.8, 3.45, 7.76]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh castShadow receiveShadow material={materials['Material #1431659660.001']} geometry={nodes.Mesh073.geometry} />
        <mesh castShadow receiveShadow material={materials['Material #1431659628.001']} geometry={nodes.Mesh073_1.geometry} />
      </group>
      <mesh  castShadow receiveShadow
        material={materials['plastic.001']}
        geometry={nodes.stand_alone.geometry}
        position={[2.95, 0.53, 4.9]}
        scale={[0.1, 0.5, 0.08]}
      />
      <mesh  castShadow receiveShadow
        material={materials['plastic.001']}
        geometry={nodes.Top_stand.geometry}
        position={[4.01, 1.79, 4.54]}
        scale={[0.38, 0.1, 0.14]}>
        <group position={[-0.05, 2.4, 1.29]} rotation={[0.14, 0, 0]} scale={[1.04, 2.21, 0.32]}>
          <mesh castShadow receiveShadow material={materials['plastic.001']} geometry={nodes.Cube015.geometry} />
          <mesh castShadow receiveShadow material={materials['Screen.001']} geometry={nodes.Cube015_1.geometry} />
        </group>
        <mesh visible={false}  castShadow receiveShadow
          material={materials['default']}
          geometry={nodes.Cube007.geometry}
          position={[-0.05, 2.4, -1.29]}
          rotation={[2.88, -0.06, 0.48]}
          scale={[1.04, 2.21, 0.32]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/npump.glb')
