/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF , useTexture } from '@react-three/drei'
import wash from './wash.glb'
import icon from './icons.png'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(wash)
  materials['Material #1431659628'].roughness = 0.4;
  materials['Material #1431659628'].metalness = 0.3;
  materials.signs.transparent = true;
  materials.signs.alphaMap = useTexture(icon);
  nodes.Cube009.material.metalness = 0.4;
  materials['Material #1431659657'].color.set("#f71d00");
  materials['Material #1431659657'].metalness = 0.2;
  materials['Material #1431659657'].roughness = 0.5;
 
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow
        material-color={'#ED8B00'}
        material={materials['Material #1431659657']}

        geometry={nodes.Rectangle140.geometry}
        position={[14.34, 3.64, -9.42]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow 
        material={materials['Material #1431659628']}
        geometry={nodes.Line002.geometry}
        position={[14.88, 4.19, -2.3]}
        rotation={[0, -1.57, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow 
        material={materials.signs}
        geometry={nodes.carwash.geometry}
        position={[11.74, 4.03, -10.32]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow 
        material={materials.signs}
        geometry={nodes.carwash_icon.geometry}
        position={[11.74, 5.43, -7.43]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow 
        material={materials['Material #1431659659']}
        geometry={nodes.Object072.geometry}
        position={[21.03, 3.32, -6.34]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh  castShadow receiveShadow 
        material={nodes.Cube009.material}
        geometry={nodes.Cube009.geometry}
        position={[14.89, 1.93, -1.02]}
        scale={[3.03, 1.95, 8.4]}
      />
    </group>
  )
}

useGLTF.preload('/wash.glb')
